### ISSUE TITLE
Record Processor Errors when tagging mods with CBash Mergable

### ISSUE THREAD

**Issue by WNovizar** [wrye-bash/wrye-bash#101]
Hi,

I got these errors when I tried to tag CBash Mergable  ElsweyrAnequina.esp and Walkabout.esp:

RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000
RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000
RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000
RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000
RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000
RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000

Normally this shouldn't be an issue since both mods aren't suppose to be merged into bashed patch anyway, but those errors will appear again when I try to create bashed patch.esp. No issues whatsoever with normal PBash. 

Thanks.

**Comment by Utumno** [comment]
@leandor: and here is an official issue for those damn debug prints

**Comment by leandor** [comment]
I already modified the print for those records in the current CBash build. It will show much more information, including the mod of origin and type of record expected.

Those debug prints were put there to catch usage of duplicated FORMIDs, but they are being triggered by NULL forms values where there are supposed to be a non-null value.

An example is the Elsweyr Anequina mod for Oblivion:

![image](https://user-images.githubusercontent.com/1095373/28233567-0eea7e4a-68ce-11e7-89d0-fa4ad46facd9.png)

Here's the mod contents in TES4Edit:
![image](https://user-images.githubusercontent.com/1095373/28233633-73396de8-68ce-11e7-8d1f-c511bc1f81ff.png)

Problem is that FORMIDs with zero value can't be indexed due to only being able to add one to the map structure that hashes them... and that's why the warning is printed.  

There's no clear way to solve this (at least for me at this particular moment... would have to think and study the code a bit more to be able to get any insights as how to solve it.)  

I don't know why that mod has those null forms, but as it is, they are being ignored and could lead to information loss IF that mod was being loaded as the active mod for modifying... all those dupes would not be written on save (AFAICT)

Perhaps one way to go about this would be to only warn about these issues when the mod that has them is the one being loaded last (as active, presumably for saving later...)

Perhaps null forms on LAND records are safe for the game engine? (Most of the cases of warnings I have seen come from those type of records)  And that's why there are mods that have them with no apparent issues? 

In that case, there has to be another way to identify them for the purposes of being indexed and added to the hash map that CBash uses for holding them, so they aren't lost on modification/save, and then that would remove that cause of warning for this particular cases, and leave it enabled for the other more dangerous cases in where the records are actually duplicated for real.

**Comment by Utumno** [comment]
Well this is then probably a won't fix - have a look at the comments here by @Arthmoor https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167394 and the reply by @zilav https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167399

**Comment by Utumno** [comment]
In general also @nycz please keep an eye ion this thread that's the de facto official thread: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=getNewComment

**Comment by leandor** [comment]
AFKmods is the official place for Wrye Bash threads now? If that's the case then I'm relieved because I was dreading the fact that the official forums moved to the awful/horrible/hideous/etc.  bethesda.net platform :grimacing:

**Comment by Arthmoor** [comment]
I don't think there's any need to "fix" this notification now that it's giving more information. I would like to know if it's possible to have the error narrow down where the NULL record is showing up. Zilav's script does work to find them. Or possibly to allow for such records to be repaired by assigning them a valid form ID within the mod.

Ultimately this is a defect in any mod that causes something like this because a NULL form ID should never be possible, especially on a LAND record.

**Comment by leandor** [comment]
Yeah, agreed. I'm puzzled on how these records showed up in Iliana's mod... also, there are more mods that have them:

Here's the case of Mages Guild Quests.esp:
![image](https://user-images.githubusercontent.com/1095373/28234503-a666f5a2-68d6-11e7-9b91-90ef8180cb3d.png)

So there has to be something that the Construction Set does on occasion... perhaps?

**Comment by Utumno** [comment]
We could open an issue in CBash for 308 maybe where we move zilav's script into CBash (for 308) and close this ? Is that possible ?

**Comment by leandor** [comment]
I'm gonna try to add a print out of the parent record's FORMID, if it's possible at all. 
But, it probably will require refactoring a bit of the CBash code to have that info available at that level.

I might also change the message for the specific case of a NULL FORMID, and display a different more appropriate warning, than the one that's being triggered now that's for duplicated FORMIDs.

**Comment by Utumno** [comment]
Hey @leandor - 👋 

Could we close this and open an issue in the CBash repo with what remains ?

**Comment by Infernio** [comment]
Closing CBash issue as `R-wont-fix` (#530).
