### ISSUE TITLE
Initializing error: can't find bartermenu.swf

### ISSUE THREAD

**Issue by codrus** [wrye-bash/wrye-bash#193]
Using Wrye Bash 305 - Standalone Executable-1840-305. Running it from in Mod Organizer. Have mopy in main Skyrim folder.  About 8 seconds into the initialization:

Traceback (most recent call last):
  File "bash\basher.pyo", line 5165, in OnShowPage
  File "bash\basher.pyo", line 3824, in OnShow
  File "bash\bosh.pyo", line 8104, in refresh
  File "bash\bosh.pyo", line 6398, in refreshSizeCrcDate
  File "bash\bolt.pyo", line 1192, in size
  File "genericpath.pyo", line 49, in getsize
WindowsError: [Error 2] The system cannot find the file specified: u'D:\Steam\SteamApps\common\Skyrim\Data\Interface\bartermenu.swf'

Stops there, doesn't finish initialization.

**Comment by Utumno** [comment]
Is `D:\Steam\SteamApps\common\Skyrim\Data\Interface\bartermenu.swf` present ?

**Comment by codrus** [comment]
No, it isn't.  The only files in there are favoritesmenu_overrides.cfg and
Translate_ENGLISH.txt.

**Comment by Utumno** [comment]
Add the file and see if this solves it

**Comment by codrus** [comment]
That file came from Show Armor Slots (for SkyUI). After I put that in the
folder it then wanted favoritesmenu.swf. So I put all three .swf files from
that mod in there. Then it wanted map.swf which is in a mod called Atlas
Map Markers v1-7 Complete.  Shockwave files, so far.

Did one more and now it wants skyui/config.txt in there. That comes from
the first mod, so I put that folder and file in there too. Then it outputs:

Traceback (most recent call last):
  File "bash\basher.pyo", line 5165, in OnShowPage
  File "bash\basher.pyo", line 3824, in OnShow
  File "bash\bosh.pyo", line 8104, in refresh
  File "bash\bosh.pyo", line 6398, in refreshSizeCrcDate
  File "bash\bolt.pyo", line 1192, in size
  File "genericpath.pyo", line 49, in getsize
WindowsError: [Error 2] The system cannot find the file specified:
u'D:\\Steam\\SteamApps\\common\\Skyrim\\Data\\scripts\\CompanionsHouseKeepingScript.pex'

It's still near the start of the process. I have about 50 mods...

**Comment by Utumno** [comment]
@Sharlikran also, any idea what might have triggered this ?

**Comment by Sharlikran** [comment]
He is using Mod Organizer, how is Wrye bash going to find the file in the data folder?

No this is not a reportable bug unless he can reproduce without mod organizer.

**Comment by Utumno** [comment]
I am not up to date with MO and all that. Can you clarify a bit ? Cause if Bash thinks the file is there where does it get this info from ?

**Comment by Sharlikran** [comment]
This is not my typical uncooperative response I would give users on the forums.  I am simply being honest.

In the threads I do not discuss Mod Organizer.  I don't use it and I know almost nothing about it.  All I said was that he is using MO, and because of that the files are not in the Data folder.  Since I know nothing about MO, you would need to research it yourself.  You [can try this](http://wiki.step-project.com/Guide:Mod_Organizer_Advanced).

WB is not at fault in this instance.  I would not consider it a bug in any way unless he can provide exact steps to reproduce it without MO installed on his system.  The DLL files provided with MO redirect all windows functions in regards to supported games like Oblivion or Skyrim.  This is done to create the virtual folders.  Therefore users can not manually copy files to the Data folder.  I do not understand MO but from what I have seen in videos by GamerPoets, when a user makes the mistake of manually altering the Data folder MO takes control of the file and places it in a folder, IIRC it is called the overwrites folder.  I don't know how it works.  

The easy answer is that users have to run WB, TES5Edit, NMM, LOOT, BOSS from MO at all times no exceptions.  Otherwise MO can't redirect the applications to the virtual folders.

**Comment by Utumno** [comment]
Thanks - I was not aware there are virtual folders in MO (lol) - this would explain it. I'll wait to hear from @codrus - if not this is worksforme

**Comment by codrus** [comment]
Sharikran is correct.  I was assuming with the popularity of both mod
organizer and wrye bash that the two would have been compatible long ago.

Just did a little more research and found that people are using them
together. I will have to figure out how they are doing it.

You may close this ticket if it isn't a wrye bash bug.


Thanks

**Comment by InsanePlumber** [comment]
Personally I do not use MO but maybe this will help.

Wrye Bash : Installation - Mod Organizer
https://www.youtube.com/watch?v=wkmTZP1SyIA

Wrye Bash : Bashed Patch - Mod Organizer
https://www.youtube.com/watch?v=W1Es06MtAZM

**Comment by Utumno** [comment]
Delete/backup your BashSettings.dat BashSettings.dat.bak files and try to start Bash - it may not function correctly - do not enable installers
