### ISSUE TITLE
Wizard does not show images

### ISSUE THREAD

**Issue by ghost** [wrye-bash/wrye-bash#209]
BAINs created one folder too deep ( ie, Right click a folder, which contains your sub-packages, and "add to archive" ), are recognised by Wrye Bash these days ( I think Lojack made those possible before handing over the project ) - Problem ; BAIN Wizards do not get pointed at the same root level - So for example images referenced in the wizard, in a Fomod \ folder in the archive, will not appear, because the wizard does not know where it should be looking
 
So for a line such as the following in a wizard ..
```
SelectOne "THE RUFFLED FEATHER - BAIN INSTALLATION WIZARD",\
  "WELCOME","\nCLICK OPTIONS .snip. INSTALLATION","FOMod\\ruffled-bain.jpg",\
```
Wrye Bash will try to find ..

    :\fomod\ruffled-bain.jpg

But actually it should be looking at ..

    :\modfoldername\fomod\ruffled-bain.jpg
 
Open the spoiler in this post http://forums.nexusmods.com/index.php?/topic/623718-water-water-and-terrain-enhancement-redux/page-613#entry25602329
I did a BAIN Wizard for The Ruffled Feather recently, and I needed to teach authors how to make a BAIN ( specifically how to create the archive correctly so as to work properly in Wrye Bash ) ..

That used to be the case all the time, people needed to be taught how to do them correctly, but since Wrye Bash now has the ability to look one folder deeper for the files in the BAIN, and the common perception these days is becoming "Wrye Bash will recognise and install a "Simple BAIN" even if it is packed one folder too deep.
So people do not realise the same does not apply for a "Complex BAIN" with a scripted Wizard.txt
 
Wrye Bash 305 standalone sort of allows one folder too deep packages ( similar to what NMM and MO allows these days ), but BAIN Wizards get a bit lost with such archives.

**Comment by Utumno** [comment]
I think I know what goes on here and it's a design flow - basically the info on the top folder is nowhere recorded and since installers info is saved i\on disc (The Instalelrs.dat precious file) it's hard to monkey patch it in - I have found a way though (I need to patch more stuff in it anyway, so I was thinking of this problem)

Before however I start working on it I need a more concrete specification for packages as I asked in #219 - in form of a wiki post preferably. That is example of packages as simple at my post in #219 (found no way to link)

But for starters can you give me minimal package structure for this one ? Is it a Complex/Simple installer or a full complex one (listed on the General tab) ?

**Comment by alt3rn1ty** [comment]
Last question first ..

Minimal package structure for this bug, the mod BAIN being discussed in the OP is a Complex package.
What would be the point of putting a wizard in either a Simple, or Complex/Simple BAIN ?
In both cases there are no options to choose from so a wizard would be unnecessary
Would a wizard even run in either of those .. Never tried personally, I have always assumed wizards were just used in Complex BAINs

------------------

Reference #219 and needing more concrete specification for packages : I Dont understand the question

Packages can be Simple, Complex/Simple, or Complex - Which are all described in the Wrye Bash readme already, in the boxout here http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#bain-convert

Visualising combinations of those is easier if you just download a heap of already made BAINs and examine them ( thats how most of us who get used to creating BAINs and associated wizards start out )
In the Wrye Bash Pictorial Guide description, I have a section which lists BAINs and BAINs with wizards if you need to find a collection of example files.

http://www.nexusmods.com/oblivion/mods/35230/?

Under "Links to Ready Made BAINs you can use out of the box"
Expand the spoiler
They are mostly simple until after Arthmoors mods, then there are complex BAINs listed

The example you gave on Feb 2nd in #219 would not be allowed, because you have put a data folder inside a sub-package of a complex BAIN ( basicly you have put a data folder inside a data folder )

Think of sub-packages as Data folders themselves ( like the games data folder but only with a selection of loose files as replacers for example, not the whole games originals ), they are just uniquely named instead of calling all of them data ( which would not be possible to have same named folders )

You could have ..

00 Data \ ( Includes Meshes \ Textures \ esp )
01 Data opt 1 \ ( Includes Different coloured textures option 1 in pink )
01 Data opt 2 \ ( Includes Different coloured textures option 2 in blue )
( No wizard so the user manually just selects sub-packages in Wrye Bash Installers tab )

Usually everyone names them uniquely to distinguish the sub-packages descriptively, but bash still treats them as multiple data folders ..

00 Core Files \ ( Includes Meshes \ Textures \ esp )
01 Pink Textures \ ( Includes Different coloured textures option 1 in pink )
01 Blue Textures \ ( Includes Different coloured textures option 2 in blue )
wizard.txt ( to automate making choices )

People who put BAINs together also tend to use the numerical naming so that options are clearer
In the above example pink and blue both start with 01 as their naming convention to indicate that if manually selecting the sub-packages only one of these should be chosen

But numerical naming also makes the sub-packages get installed in the order the BAIN creator wants.

All a BAIN creator has to go on really is the brief description in Wrye Bash readme as a basic guideline .. From there, and depending upon the objective of the mod and what files / options / alternative choices need to be included, it depends on how logical the creator thinks and applies that logic to the series of overwrites that the sub-packages are

( aswell as different installers potentially conflicting, and the install order being important - The sub-package order of an individual installer is also important, if ALL sub-packages are selected to install, then where there are conflicts within the same installers sub-packages then Wrye Bash installs them in numerical / alphabetical order - Last installed wins as usual )

Wrye Bash Pictorial Guide walks you through making BAINs, aswell as just doing the basics.

Utumno I would suggest ( though you may feel it unnecessary ), to do my walkthroughs once, and you will then have a better understanding of BAINs and how you put them together / make decisions about designing a BAIN structure - Then you will also understand why I dont understand what you mean by needing examples, those seemingly simple descriptions of Simple, Simple\Complex, and Complex BAINs are all you need really.

Though the description currently in Wrye Bash Readme boxouts of what files can be included and valid folders only gives data content as being valid for Oblivion, those obviously have variations per game - I think all of those were listed IIRC in Skyrim.py and Oblivion.py ?

**Comment by alt3rn1ty** [comment]
Just thought - One thing that may be confusing to someone new to BAIN creation here ..

That fomod folder

Wrye bash will not install any of its content, but if directed by a wizard it will look inside that folder for any images ..

The fomod folder is needed by OBMM or NMM, usually their is a script and images which are used as resources for OBMM or NMM to automate their installs of the files in the zip

Quite a lot of people will make a multi-mod manager friendly zip which has a wizard for Wrye Bash in the root of the archive ( at the sub-package level ) ..

.. And also include a fomod folder ( plus the relevant scripting in there ) for OBMM or NMM to also automate installation of the same files from the same archive

So a mod author can have one file up there on nexus, which any mod manager can install automatically.

If one mod manager ( OBMM or NMM ) will be looking in the fomod folder for the scripted installers images .. Then the Wrye Bash wizard may aswell use the same images for its presentation ..

.. Hence why "The Ruffled Feather" mod has a FOMod folder in the root of the archive, and why Wrye Bash Wizard is directed by the author to look in there for its images

Anything else that is in the FOMod folder will be ignored by Wrye Bash, same as OBMM or NMM will ignore the Wizard.txt

**Comment by alt3rn1ty** [comment]
OK will also have a go at some examples of Simple Simple\Complex Complex

`meshes folder
 textures folder
 modname.esp`

Multi-select all the above, and choose Add to archive = You now have a Simple BAIN zip, all the above are in the **Root** of the archive

Now put all the above inside a Data folder
Right click the Data folder and add to archive ( so you end up with a Data folder in the **Root** of the archive ) = Simple \ Complex BAIN - The Data folder in this case could be called anything, but would be treated as a Data folder ( Sub-package ) no matter what the name of the folder is because it contains all files that you would normally find in a Simple BAIN

Now have multiple copies of that data folder, all with Unique names, but all of them containing files that you would normally find in a Simple BAIN
Multi-Select all of these sub-packages, and choose Add to archive so that all these sub-package folders end up in the **Root** of the archive ..
.. You have created a Complex BAIN


Now back to the problem of this bug

Put all the sub-packages created in the complex BAIN above, inside another folder

This new single folder ( which now contains all your sub-package folders, so you have created multiple data folders inside a data folder ), is sitting in a new **Root** ( a folder level above the sub-packages level )
Mod creator just selects this one folder, and zips it up into a BAIN which is now one folder too deep, effectively you have a Data folder now containing multiple Data folders and the wizard.txt is also sitting inside this master data folder

When the wizard is executed, BAIN starts looking for paths to images at the Root of the archive

In the problem case its taking the Root of the archive as being where the main folder is, so paths to the images are wrong, because it cant point to a fomod folder which is inside a folder not specified in the wizard

So even though Wrye Bash is allowing one-folder-too-deep packages these days, its not adjusting the root of where the wizard executed from to be one folder deeper than where the root currently is


Hope that all makes the problem a bit clearer :)

**Comment by Utumno** [comment]
@alt3rn1ty: well thanks - a bit too much info to digest - most of it I know - hey, I program Bash :D

I am actively rewriting the docs and revisiting core BAIN code - so my questions were a little deeper. Bear with me please cause this is the one opportunity to _once and for all_ document **and **code what goes on exactly.

I referred to some deeper issues in #219 (see couple layouts I posted there) - but I still believe that major help would be _a wiki post with BAIN packages_ - if you could do that we could then discuss by editing that post and address the deeper issues I referred to (mainly docs placement, root folder allowed files, ini tweaks installation, wizard txt and wizard images placement and skips). But I need some basic example layouts to begin.

The code does strange things at points allowing for peculiar exceptions. I tried to document what the code does (while deciding on some edge cases): https://github.com/wrye-bash/wrye-bash/compare/utumno-wip

See the diffs in advanced and general readmes to see what added then read them in the readmes. They come with the standalone I posted.

As you see I added some new sections - have a look. I try to define package layout - for instance did you know that for complex packages:

> The top level subdirectories (known as subpackages) <b>must not have the same name as any of the regular game subdirectories for this game.</b>

Well I didn't, I learned that from the code and from the report by Imstearn (see OP in #219: http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/page-6#entry24315318). Things like that should be in the docs in **bold**.

So I went ahead and documented what goes on _from the code_ . Which exactly are the regular game directories, what is skipped (I refer to fomod there but did you know there is a "wizard images" directory ?) and many other small print. _It's this small print we need to finalize._

A section in the wiki with conventions for BAIN packages is a nice addition but the most important is a rigorous specification based on the docs I am writing and your input. Adding pictures later would be great but simple code listings would be enough for now, as:

Simple package:

   some.esp
   Textures\
      subfolder\
         some.dds

Left as an exercise: where readme goes ? ;)


------


Re: issue at hand - link me to the package please and let me see if it's possible. The code for deciding what a package is (simple, complex, complex/simple or invalid) is complex itself and fixing is blocked by the lack of specification I referred to above (down to the minute details I need to know when I am coding those ifs). Still it may be possible to do what we need here - but it will require hacking the Installers.dat.

In the popular culture:  complex/simple packages are type = 2 packages internally, that is _complex_. I could imagine it would be a complex package the one you speak of but internally it's the same - and complex.

Did I say it's complex ?

**Comment by alt3rn1ty** [comment]
Erm, well linking you to the package is now pointless - Since I told them how to make a BAIN without having it one folder too deep, they ( SparrowPrince and TechAngel ) now both package a BAIN how we traditionally package them, with sub-packages in the root of the archive [url=https://i.imgur.com/m6mVTkL.jpg]screenshot[/url].
At the time I made the report for this bug, the detail of that mod going wrong was correct ..
But anyway its here http://www.nexusmods.com/skyrim/mods/13268/?

There have been many other mods out there ( I cant put my mouse on one right now ) which have been packaged one folder too deep, I dont know if the Skyrim community have been following someones video which was popular or something but a lot of people are used to just packaging a folder that a project is inside.
So there are lots of mods out there which only need to be simple mods, but due to the practice of how people use archivers these days they end up being packaged as Simple\Complex ..
And on the few occasions they repackage a Complex BAIN they automatically archive that package too one folder too deep .. because for most people its simple doing it that way.
I think it was Lojack who eventually gave Wrye Bash the ability to look one folder deeper, due to the amount of people complaining that Wrye Bash was the only mod manager which could not do that out of the big three, but I dont think when Wrye Bash opens such an archive it then adjusts any possible pathing problems of a wizard pointing at files within the structure of the archive.
And then this leads to images not being displayed, because Wrye Bash is not finding them. Its starting a path search for files from a Root that is wrong.

I realise you program it now ( and very well too ), so apologies if a fair bit of the above was teaching you to suck eggs, but there have been a couple of times I noticed you mention you are unused to BAIN, or its syntax, or how they are made, or wizards ( in various forum posts you made ) .. So I gave as full a description as possible.

This divert to GitHub ( and the other calls for alt3rn1ty here I just noticed in the last couple of days ) has taken me away from what I did promise to do this week and address those readme's ..
I have not started doing those edits yet. Tomorrow I will be digging up the garden in preparation for our new shed so will be offline for a few days now.

Please stop inviting me to join something ( apparently there is an invite somewhere, probably blocked because my modus operandi is to turn off all kinds of notifications on any kind of forum I join ), but I did say a long while ago that I did not wish to become too involved in any more projects, because my life these days is too heavy, complicated by operations / illness and a need to keep my career going.

I do wish this project the best, its a shame the old team burned out but its also obvious it really needed your hand in the project to overhaul it. And I also appreciate its too much for one person.
I offer what I can when I can, but do not wish to be seduced into other aspects, RL is far more important to me these days than this game hobby.

**Comment by Utumno** [comment]
> so apologies if a fair bit of the above was teaching you to suck eggs, but there have been a couple of times I noticed you mention you are unused to BAIN, or its syntax, or how they are made, or wizards ( in various forum posts you made )

No worries - it's this small print I was worried about

> Please stop inviting me to join something 

Haha - I was inviting you to join this repo as a member but ok I will remove the invite no worries

> I offer what I can when I can , but do not wish to be seduced into other aspects, RL is far more important to me these days than this game hobby.

All the best with RL !! Ok no worries - just keep offering your much needed advice when you get some time - I will refrain from notifying you from issues but no need to delete your account - just in case you find some time to post (to) an issue here.

Re: wiki - you had written a wiki post here that's why I asked but yes it's some work to document BAIN structure so forget about it. If you come round to editing the readmes so much the better - if not, no worries I will do that.

Always a pleasure to see you around so don't totally give up your game hobby :)
