### ISSUE TITLE
Lock load order

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#210]
Bash should be able to restore the load order of any game that it manages on restart or on getting focus to a saved one.
The functionality is present for Oblivion but as at the time load order == mod times it is coded as "lock modification times".

- [x] save snapshots on every load order change - maybe make a different issue (the code is not yet ready but getting there - edit: #256)
- [ ] move this code into load_order.py and make it applicable to Skyrim/fallout4

**Comment by Infernio** [comment]
@Utumno `Lock Load Order` doesn't seem to care if an external program activates or deactivates plugins. Noticed this when debugging my Morrowind LO implementation because I thought it was broken, but then tried it on SSE and it didn't do anything there either.

To reproduce:
 1. Tab out of WB
 2. Edit `plugins.txt`, remove one of the asterisks
 3. Tab back into WB -> no LO popup

I guess this is on purpose? The documentation is a bit unclear about it, so maybe adding an extra toggle for those who want WB to lock actives as well might be helpful?

**Comment by Utumno** [comment]
Hmm was not on purpose for one should have broken in the meantime, but yes this API needs some smoothing out (it did was a complex problem) - let me have a look too
