### ISSUE TITLE
Highlight the masters of the bashed patch

### ISSUE THREAD

**Issue by Forlini91** [wrye-bash/wrye-bash#213]
Is it possible to highlight or put a sign on every esp/esm which is required by the Bashed Patch?Sometimes, when trying to organize my mods or find the culprit of some bug I deactivate an (apparently) innocent esp and the chaos unleash because it deactivate the Bashed Patch and so all mods it require in a deadly combo-chain.

**Comment by Utumno** [comment]
Forum discussion in http://forums.bethsoft.com/topic/1518379-wrye-bash-thread-103/page-4#entry24027244

**Comment by Utumno** [comment]
Closing this as won't fix - cause one may have numerous bashed patches and this can make life hard, but most importantly because I implemented an undo load order feature in 307 which makes it super easy undo the chaos. Just hit Ctrl+Z with focus on the mod list and miracle! The deactivation is undone. Feel free to comment if you need something more
