### ISSUE TITLE
Some GitHub Readme info/media is outdated/broken [partially resolved]

### ISSUE THREAD

**Issue by titaniachkt** [wrye-bash/wrye-bash#215]
Should this issue even be in the wrye-bash section? Seems more a [github] (https://github.com/wrye-bash/wrye-bash.github.io/issues) issue. Apologies in advance if that was a better place.

*Taking a look at the rest of the readme, lots of info is probably now outdated, so updating this ticket to reflect that*

**Link to master file readmes**:
* [General] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html)
* [Advanced] (http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html)

#### Part 1: ~~Missing Image urls~~ Screenshots work, icons and program icons still missing

Seems to happen with all the readmes linked from the [nexus] (http://www.nexusmods.com/skyrim/mods/1840/?), most noticeably for the General and Advanced readmes (didn't see any for the Technical readme and Version History).

All 4 links work
~~Example urls: (both return a 404)~~
[General] (http://wrye-bash.github.io/bash/images/readme/installers-1.png)
[Advanced] (http://wrye-bash.github.io/bash/images/readme/saves.png)
~~https links are broken too, btw~~
[General] (https://wrye-bash.github.io/bash/images/readme/installers-1.png)
[Advanced] (https://wrye-bash.github.io/bash/images/readme/saves.png)

Tested on Opera and K-Meleon, win xp sp3 (should it really matter though). Scripts enabled. 

#### Part 2: Some referenced programs are outdated/no longer maintained

Noticed that some of the external programs in the [Launching Applications] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#launchers) section are depreciated, most noticeably being [BOSS] (http://www.nexusmods.com/skyrim/mods/6) (404).

Disregard this, didn't see the [Custom Launchers] (http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#launchers-custom) section in the advanced readme
~~Also, are the list of programs mentioned in the [Other Applications] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#launchers-apps) section linked in the Wrye  Bash launcher bar?~~ 
~~I ask because Notepad++ shows up, but not others like GIMP. (default install folders in Program Files for Win7)~~

#### Part 3: Miscellaneous

The  [Known Bugs] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#trouble-known) section has no links to the GitHub tracker (this site) which is present on the nexus page.

**Update:**
Sharlikran said:
> I'll add a link for the Issue Tracker so people know where it is.

Also not sure if the Common Issues section in the general readme are kept updated.

--------------------------------------------------------------------------------------------------------------------

(P.S. Thanks for porting WB to TES5!)

**Comment by Utumno** [comment]
Yep should be [there](https://github.com/wrye-bash/wrye-bash.github.io/issues) but now it's here let's discuss it here ;)

RE: 2 and 3 - can you provide me a patch ? just correcting the html and sending it to me would be great (post a link here) - bear in mind that the readme in this repo has changes - latest one here: https://github.com/wrye-bash/wrye-bash/commit/c02047abd05bcd4334aaf65e0817a4569724b7d7 - so preferably patch this latest version

RE: 1 - heeelp, lol, wtf

Pushed a branch with the images : https://github.com/wrye-bash/wrye-bash.github.io/commits/utumno-306
 and made it to the default branch but no joy

Any ideas ?

Image links in the readme  are in relative path form `<img src="../bash/images/readme/saves.png" alt="Saves Tab"/>` - could it be that ? Hope not

**Comment by Sharlikran** [comment]
It's not perfect but I have had the [links updated](http://sharlikran.github.io/wrye-bash.github.io/) for a while.  I just haven't done anything to the main page so there are only links to the readme files.  I don't have time to update it right now but I will try to add some of the suggestions later.

**Comment by Utumno** [comment]
As I commented on one of your commits, changes should be performed on this repo and then just mirrored in the other - so we are sure the local readmes (the ones that ship with Bash) are ok. Ah and yes this is up to you sharl :)

Be sure to include the info by you and @alt3rnity in #192

**Comment by alt3rn1ty** [comment]
@Sharlikran 
You have incorporated the MI and Current LO info here ..
http://sharlikran.github.io/wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#mods-details

In the "Masters list" description

But have not done the same for the saves tab boxout ..
http://sharlikran.github.io/wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#saves-overview

Thats all that needs done from my edits

**Comment by Sharlikran** [comment]
titaniachkt, for your first concern about the images yes it's just GitHub.  I have my own fork and I have the images working on it just fine.

For the second concern my approach to outdated links is that I don't really feel like hunting down all the updated links to sites that are no longer in service.  However, I don't want to remove the programs from the list because I don't like removing historical information from anything.  Back when this was created I doubt the internet tools (Google) were as good as they are today.  For Morrowind, Fallout 3 and such most people turned to Wiki pages and readmes.  The Oblivion Wiki is pretty much the bible when it comes to anything.  We all know Planet Elder scrolls is pretty much dead at this point and some of the programs may not be hosted anywhere at all.  However, the programs should stay in the list.  Users can ask on the Nexus or Beth forums about them if they like. 

If you find links feel free to fork the [wrye-bash.github.io](https://github.com/wrye-bash/wrye-bash.github.io)  and update the links in a pull request.

Lastly for known issues and bugs.  I don't feel the known issues or common issues needs to be updated.  Most truly common issues are easily resolved with some common sense.  For example when TES5Edit says that Skyrim.esm must load before Update.esm then the person has not run the Skyrim Launcher, BOSS, or LOOT and their load order is not correct.  When mods are not in the right order for Wrye Bash it's the same thing.  You need to edit BOSS or LOOT user lists/metadata and sort your mods.  If the masters are not in the right order that is the authors fault for not dating the masters correctly. The Skyrim CK still uses the date stamp of the file even though the game does not.

I don't want to add common issues that are created by misuse of third party tools by users or resolved by proper use of other third party utilities.  The readme should pertain to only Wrye Bash.  So adding when you load order is out of whack do this has nothing to do directly with Bash itself.

You may read the readme, alt3rn1ty might, and so on but most people just post in the forums and don't even know Wrye Bash has a readme.  Then you have others who know there is a readme but take a TL;DR approach to it and think it's faster for them to ask in the forum.  Plus a lot of people want a person to tell them it's okay to do something.  They feel if the other person said it's okay and that they have done it then it must be okay.  I could keep going and going about all the user behavior I have seen over the years.

What I am going to do is make sure I have added alt3rn1ty's description of the colors is in the readme and make sure the icons show up so that the MI and Current LO are explained for the mods tab and the Saves tab.  Then I'll add a link for the Issue Tracker so people know where it is.

**Comment by Utumno** [comment]
Great two points:

 - no the images were not showing cause basically they were not in the repo (and some of them are still not there). I will wait for the updated readmes to be merged into this repo and then  push them to the other along with its images.
- what titaniachkt is asking is a link to this tracker - which is a good idea

**Comment by titaniachkt** [comment]
@all 
Sounds great! Can't think of any rebuttals to the above at present

@Utumno 
Thanks!
Not sure what you(?) changed exactly, but the most of the images linked in the wrye bash github.io's work now! Namely the screenshots, as the ones in the OP (all animated pngs work too, from what i've checked). 
What **doesn't** work though, seems to be the icons and such ([wand icon] (http://wrye-bash.github.io/bash/images/wizard.png), [checkbox icons] (http://wrye-bash.github.io/bash/images/checkbox_green_inc.png) etc)

Most noticeable are in sections [4e] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#bain-symbols) and [5c] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#load-symbols), 'What Symbols & Colours Mean' of the general readme 

Note that all images and icons (at least from what I've checked) currently work on Sharlikran's fork of the io as they said

>actually if you volunteer to go through the readme you have a cookie :)

Is this for me? If so, I'd be glad to take a look at both general and advanced readmes (even with no cookies) and make a report of what info may no longer be up to date. Stuff like:
* referencing oblivion in places where [game] would fit, where [game] is skyrim, FNV, other
* references to outdated mods/utilities like BOSS or oblivion-specific tools; etc
* updating the mod links section (tes4, tes5, fnv..other?)
* anything else that makes the readmes more accessible and allows the content to remain valid for as long as possible
(See also the bit about forking the w-b.github.io from Sharlikran below)

---

@Sharlikran 
>I don't want to add common issues that are created by misuse of third party tools by users or resolved by proper use of other third party utilities.

Makes sense; totally agreed

What about common issues specific to wrye bash? (similar to what's currently on the readme, though most of those look like python-specific issues which are *technically* a WB issue anyway)

>I'll add a link for the Issue Tracker so people know where it is.
>what titaniachkt is asking is a link to this tracker (Utumno)

That would probably be the easiest thing from the sound of it, yes. Looks like we're in agreement!

What about linking to specific repositories on the site, but for general categories of issues/bugs/suggestions (separate links for program specific issues, manual/readme issues, suggestion, etc) so those unfamiliar with git/vcs systems can contribute with the least worry about putting things in the wrong place.
At the very least, program-specific issues should probably be separate from document-specific issues

>If you find links feel free to fork the wrye-bash.github.io and update the links in a pull request.

Sure, I could give it a try (see my last response to Utumno just above yours).
Should that be a devname-* branch?
I'd have to read up more on the Contributing Readme.md ([this] (https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Branching-Model-&-Using-The-Repository) and [this] (https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Branching-and-merging-to-dev-using-rebase)) first though

---

On a similar but unrelated note, what do you all think about adding some more definitions of acronyms in the general readme's [Glossary] (http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#intro-glossary) section?

The most important missing one (present only on Sharlikran's fork, under the [Masters List] (http://sharlikran.github.io/wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#mods-details) item in the table ) which currently comes to mind is MI - Master Index 
Couldn't find any mention of it in the master readme file (advanced or otherwise)

Another suggestion is having a glossary/appendix of sorts in both general and advanced files which would contain a bunch of useful info in one section without having to comb through multiple docs. Maybe something like this in the table of contents:

* [number]. Glossary or Appendix - whatever sounds better
    * a. List of Acronyms and/or terms used in both docs. <- basically the Glossary section from the general readme, plus other misc. terms that may be added to both for convenient reference
    * b. List of all colors for all sections (installers, mods, saves) and their meanings. Would include text colors, icons, icon colors, background colors, and probably something else i'm forgetting
    * c. List of all tables referenced/menu explanations.
    * d. Something else that's useful when easily referenced

Hrm..could this be a separate file altogether? Maybe 'Reference Index' or something less library-sounding.

I've noticed that one of the biggest reasons people are hesitant to use WB is the rather complex, highly semantic gui, (which is great btw), and as Sharlikran pointed out - The average user has little to no interest in poring over readmes and tables, much less multiple ones.

So having a separate file solely as a quick reference of sorts may help make that less daunting.
Maybe even as a pdf/epub or something bundled with releases

I'll add the above suggestions to my fork so you can see what it'll look like.  Can't say how soon that would be though

--

Speaking of bundled files, the local readmes for WB (html) in the x/Mopy/Docs folder all load the images normally. This includes stuff like the icons (+ signs, wizard want icons), program screenshots, and external program icons (BOSS, Maya, Audacity etc).
The only one that **isn't** loaded is the external link icon (blue arrow pointing northeast) for some reason.
Those were tested with an offline html renderer, and the external link icon points to a local browser location, so that's probably why.

..maybe

--

Updating the OP with the following:
* Modified topic 
* Adding links to the main io repository and Sharlikran's fork
* Marking the 404s as resolved

**Comment by Sharlikran** [comment]
What op? I don't want my fork linked to anything.  I like to do what works for me.  I don't like the welcome page that GitHub auto generated but I also don't want to change it. It doesn't matter to me how it looks.  That's why I like my forks.

I'll try to get the changes that can't go into the official read me later.

**Comment by titaniachkt** [comment]
OK, sure thing, removed your link for reference then (the OP for this issue)

That last part about separating changes would be really useful, thanks

**Comment by Utumno** [comment]
Sorry titaniachkt the walls of text are not allowed here - please edit your post and leave only relevant info - read previous posts

**Comment by Sharlikran** [comment]
I went to the trouble of separating my changes for the bash tags from the changes needed so that you can use the wrye-bash.github.io as an online link for the documentation.  When I went to make a pull request to add a branch for titaniachkt to work with so that work isn't being duplicated, the pull request gave me the indication that it would change the master branch.  I don't want to commit to the master branch so I canceled it and closed the pull request.

Because of GitHub requirements you have to have a gh-pages branch in order to view the documentation online.  Because of that I'd have to delete my fork, make changes directly to the wrye-bash/wrye-bash.github.io and make another fork.

I like having my own fork for my own personal reasons.  So at this point I don't know what to say and I'm not interested in this.

**Comment by Utumno** [comment]
Ok go on working on your fork - will get the changes from there - keep them separated

**Comment by Sharlikran** [comment]
Well and to clarify things a little more I'm not mad or anything.  It's just that GitHub has the requirement of the gh-pages branch.  That's what is messing this all up.
![image](https://cloud.githubusercontent.com/assets/1912426/8151201/1594e60a-12bc-11e5-8d09-095c9b73d143.png)
As shown above I can separate all the branches I want.  However, gh-pages has to be rebase off of whatever branch has the changes that users will see online.  So if titaniachkt makes a branch named titaniachkt-updates then none of his changes will show up online unless gh-pages is rebased off of his branch.

More or less the wrye-bash/wrye-bash.github.io can have any number of branches as you want.  However, gh-pages is the only one that matters.  It's as if you were to do it the right way, if there is a right way, you would only have a gh-pages and nothing else.  No master and no dev branches, just gh-pages.

**Comment by Utumno** [comment]
Nice Sharl! Getting to know git I see

Up to and including minor typos I think should be in master - let me do this later

Re:gh pages - master is ok too I think - as you see we can see the readmes online. Maybe gh pages needed for index.html (front page) ? Not sure about that

**Comment by Sharlikran** [comment]
Yeah it has to be gh-pages or the site can't be referenced as wrye-bash.github.io as [shown here](https://help.github.com/articles/user-organization-and-project-pages/).  However, I updated the zip and tar.gz links so if you use those you can download the files quickly and easily.

**Comment by Utumno** [comment]
I think that in the link you posted we fall into "Organization page" case - so master - yours, being a "project pages" case needs gh-pages

**Comment by Sharlikran** [comment]
Added the [color scheme](http://sharlikran.github.io/wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html) for the masters of the mods and save games.

**Comment by Sharlikran** [comment]
I [updated the color scheme](http://sharlikran.github.io/wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#mod-masters-symbols) of the check boxes for the masters.

**Comment by Utumno** [comment]
:+1:

**Comment by Utumno** [comment]
@titaniachkt: thanks for editing the post - added the info to the readme: https://github.com/wrye-bash/wrye-bash/commit/87dc8d57788e2fff1df283f045a5495b8fa2d482 ;)

This heads up was very useful actually cause broken online readmes are a nono - so thanks. The readmes are ready so let me close this when I push them to the readme repo

@Sharlikran: here are your changes: https://github.com/wrye-bash/wrye-bash/commits/sharlikran-readme-updates

Squashed them a bit and replaced a funky unicode char but they are your changes exactly - should I merge to dev ?

**Comment by Sharlikran** [comment]
Yeah that looks fine.

**Comment by Utumno** [comment]
Alright - will do ASAP. When I finally get round to it I would suggest that you transfer the tags edits to your skyrim patchers branch (maybe squashing them to one commit)  - as basically we edit the readme here and then copy paste it to the other repo (we have yet to find a better way #56). That will only leave the gh-pages stuff on your fork - cleaner that way. And thanks for adding the masters colors - good job and needed :+1:

**Comment by Utumno** [comment]
Online readme better than evah - good catch there @titaniachkt :)

Thanks everybody !

**Comment by Utumno** [comment]
Related to #67
