### ISSUE TITLE
Wrye Bash 305 - Clean Data does not preserve SKSE files

### ISSUE THREAD

**Issue by ghost** [wrye-bash/wrye-bash#218]
When you right click the Installers Header Bar, and choose Clean Data

Wrye Bash does not preserve files installed for SKSE
IIRC files associated with OBSE for oblivion are on a preserve list when this function is invoked
I think the same needs to be applied for Skyrim users of SKSE

http://skse.silverlock.org/

After install see Scripts folder, and Skse folder, both in data
Additional to the installation, users may also make an ini file for special skse settings

data \ scripts \ ( many )

data \ skse \ plugins \ ( variable per user )

data \ skse \ skse.ini

**Comment by Utumno** [comment]
Thanks for the reports - don't add a 219 however I am getting a bit overwhelmed - wait till release - unless of course you find a show stopper - ah and you are now officially a team member ;)

**Comment by alt3rn1ty** [comment]
Yep apologies for another issue found but its no biggie so can wait.

Urk, hopefully I can contribute something worthwhile as a new monkey

**Comment by Arthmoor** [comment]
One does need to keep in mind that the contents of Data\Scripts that SKSE installs are replacements for vanilla .pex files, and the entire purpose of "Clean Data" is to get rid of files added by mods so the game can be reverted to a vanilla state.

**Comment by Utumno** [comment]
@Arthmoor - so what should be done you think ?

**Comment by Arthmoor** [comment]
I think it should be left alone and continue to behave as it does. People simply need to be aware that SKSE is not vanilla, so cleaning the folder means you need to put it back like anything else.

I also think that an exception having been made for OBSE was wrong for Oblivion, but that was done ages ago so I guess that ship has sailed.

**Comment by alt3rn1ty** [comment]
Actually I think I have found something that could be utilized already ..
.. Its just something I have never used, see the following screenshot
http://i.imgur.com/YwazS1y.jpg

Monitor External Installation

Its short toolbar description reads 
"Monitors the data folder during installation via manual install or third party tools"

I would imagine if you have this selected ( it is off by default - Never noticed it or used it before ), then anything that installs between sessions of Wrye Bash being loaded ( ie, extra file appear in the data folder that were not there before on the last Installers Refresh of the data folder content ) .. Then those files become untouchable by Wrye Bash Clean Data ? ( possibly introduced by Lojack as a measure to prevent Wrye Bash uninstalling / deleting files installed by NMM since using multiple mod managers has become widely adopted since Skyrim came along )

**Comment by alt3rn1ty** [comment]
Found it doesn't do quite what I thought but it is damned useful for this topic
Select
Monitor External Installation

Then you will be asked to install your files ( keep Wrye Bash loaded )
http://i.imgur.com/wipTSWr.jpg

Then click okay afterwards
http://i.imgur.com/MTgX35n.jpg

It basicly does a refresh, gathers up all the diffed files, and helps you to create a project ( which you can obviously turn into a BAIN for re-installs..

.. and they would be henceforth protected against Clean Data :)

I'm closing this issue as not needing anything done

**Comment by Utumno** [comment]
@alt3rn1ty great - do the accept the invitation too

Btw - readme feed and care is always ana issue - so if you come round to it...

**Comment by Arthmoor** [comment]
Oh, that's pretty sweet. I'd never noticed it there either. Perfect for SKSE in fact :P

**Comment by Utumno** [comment]
Ahhh finally testers for this one ahahaha

**Comment by alt3rn1ty** [comment]
Just following through on this one ..

Used "Monitor External Installation" to create a Project out of the SKSE scripts and INI
Made a BAIN out of it
Deleted the Project folder and all contents
Installed the BAIN

Looked at the properties of my data folder = 2814 files

Used "Clean Data"

And then looked again at the properties of my data folder = 2813 files

:) - "Clean Data" purged my Smashed Patch.esp, but everything else was left installed.
