### ISSUE TITLE
Tweak Settings: Use as few masters as possible

### ISSUE THREAD

**Issue by Forlini91** [wrye-bash/wrye-bash#226]
See [this comment](https://github.com/wrye-bash/wrye-bash/issues/226#issuecomment-552243630) for a summary of what's requested.

Original Issue Description:
> I found a bug in the way the Bashed Patch (I've only tested PBash).
>
> If you have an esp which change one of those game settings which can be altered by the patch (like "fEssentialDeathTime" or "iArrowInventoryChance"), and let the bashed patch override it with the relative Tweak Setting, then the bashed patch will register the GMST as belonging to that esp instead of the main esm. In other words the GMST index (the first 2 chars in the FormID) will be that mod's index instead of 00 (main esm).
>
> An example is better: 
> First, here's my Bashed Patch config: https://drive.google.com/file/d/0B5L6ymIjm7muY3N1c1FhbWlVSVk/view?usp=sharing
> Here's a screen of what's happening on my end: fEssentialDeathTime and fPlayerDeathReloadTime (and few other settings) are changed by both my esp NehrimMod (which require all above Nehrim\* esps/esms) and the Bashed Patch tweaks. As you can see in the bottom right corner (the bashed patch details), those settings have index 03, which in the master list is NehrimMod.esp, but those settings don't belong to it!
>
> ![image](https://cloud.githubusercontent.com/assets/12827228/8968523/0ff36fa0-363e-11e5-8d3c-f1c6524de34f.png)

**Comment by lojack5** [comment]
Seeing as the game engine accesses GMSTs (and a few other records) by EditorID and not FormID, this shouldn't be an issue (and hence the reason why it's done this way).  Unless you can find a specific case where this is actually preventing the GMST from working?

IIRC it was done this way specifically to prevent pulling in unneeded masters.

**Comment by Forlini91** [comment]
I think it doesn't cause any issue as load order is what really matter after all the changes/overrides.

If this was the author's intention, then I'm getting the opposite result: the bashed patch pull in my mod as unneeded master, because nothing is taken/altered in that esp from the PBash.
I suppose if many esps change many game settings and you use the bashed patch to override them all, you will end with a bunch of unneeded masters.
The main esm is almost always a master in the bashed patch, so I guess using it as master for all GMST should effectively avoid taking random esps in the load order as masters just because they alter a GMST.

**Comment by lojack5** [comment]
I don't remember the exact code, but one of two things is happening in your case:
 1. Those are from a GMST tweak, but Oblivion.esm doesn't exist (which is where its normal FormID would come from).  Some GMSTs don't even exist normally in Oblivion.esm, but the "belong" to it, so it could be some edge case of not finding Oblivion.esm when dealing with a Nehrim install.  Not sure why it would pick 03 as the ModID for the new record though.
 2 Those are getting imported from another mod, but the mod is left inactive, so PBash has to give it another FormID (again not sure why 03).

It's possible the PBash might be reworked to make GMSTs be given the ModID of the main ESM, or of the Bashed Patch itself.  IIRC the reason this wasn't the case already is that even though the FormID of the GMST doesn't matter, we wanted Bash to attempt to keep all GMSTs as the same FormID in most cases, so it doesn't look weird and we don't get questions like this.

Seems to me the code just needs a little patching to make it less obvious when it has to change/create a FormID of a GMST.

**Comment by Infernio** [comment]
The reason WB tries really hard to use existing fids before injecting any is that injecting is *really dangerous*. If another mod happens to inject something else to one of the fids WB injected, all kinds of things could happen, ranging from both the mod and the GMST not working to a full on CTD when the game tries to read some record type and gets a GMST instead.

A probably worthwhile tweak would be to try and optimize the algorithm to include as few masters as possible, which would be especially important for ESL games (since the numer of mod masters is still limited at 255, every master slot is precious).
For example, consider this situation:
- FirstMod.esp contains the GMST `00BEEF fArrowAgeMax`
- SecondMod.esp contains the GMST `00DEAD fArrowAgeMax`

Let's say that FirstMod.esp is already a master for the BP for some other reason (e.g. some imported graphics) and we want to apply a tweak to `fArrowAgeMax`.
We could simply override the `00BEEF fArrowAgeMax` record from FirstMod.esp, without needing to add a second master. However, if I recall correctly (and I'm not sure I do, TODO double-check this), the BP would instead override `00DEAD fArrowAgeMax` from SecondMod.esp since it comes later in the load order, unnecessarily adding it as a master in the process.

So I'm marking this as an enhancement request to change the behavior of Tweak Settings to include as few masters as possible.

**Comment by Infernio** [comment]
Dropped `M-good-first-issue` as this is obsoleted by `inf-312-tweak-pooling`.
