### ISSUE TITLE
Boot sequence

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#244]
bash.py needs to define a clear boot sequence:
- [x] in bash.py wx must be imported once and for all and booting should simply abort early with a tkinter error if wx is not available - no use for all the Tkinter hocus pocus (I do not mean we should completely drop it - just clean it up). ->https://github.com/wrye-bash/wrye-bash/commit/c75fd17408c858e440ebc558ed3089e4a26d4a4f
- [ ] import order must be clearly specified and documented -> superseded  #390
- [ ] the various logs must be unified - bashbugdump.log to rule them all -> superseded  #352
- [ ] more....

See https://github.com/wrye-bash/wrye-bash/commit/e19237c18f14de839d5724051ddea67a600a67fa and #184

**Comment by Metallicow** [comment]
+1 for ... especially debugging...

 * ExceptionHookDialog - Hook in a custom sys.excepthook, right from the beginning: wx.Frame/Dialog at the beginning, if not failed by then... otherwise show the TK opps dialog. It helps a lot when debugging, otherwise we use the ancient old-school bat/logging/txt dump(which is still useful BTW).
Center the on-wards development around a hand-built simple GUI debugger. 

SourceCoder has one of these, but usually most of the code is app specific, so to say...
Hook the sys.excepthook in early after imports, that way it catches all exceptions afterwards and pops up as a native dialog.
A STC setup for python even syntax highlights it(exceptions/etc...), and provides options for opening the offending lines/files... and other custom debugging measures, before [ABORT] button is pressed if necessary.

**Comment by Utumno** [comment]
Put to the backburner for now

**Comment by Utumno** [comment]
Superseded by #352, #390, #373
