### ISSUE TITLE
cint package

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#264]
Catch all issue to start investigating/splitting/fixing cint.py
- [ ] We are loading all fallout classes for naught - must be split into a package with a structure similar to the games one
- [ ] we must investigate if/how we can compile the dll for linux
- [ ] Error messages - whenever an error is encountered we just return: `"Function returned an error code."` - :nocomments:
- [ ] the eternal error `RecordProcessor: Warning - Information lost. Record skipped with duplicate formID: 00000000`

**Comment by Infernio** [comment]
@wrye-bash/bashers I guess it's time for layout discussion. My first idea was:
```
bash
|- cint
   |- __init__.py
   |- falloutnv.py
   |- oblivion.py
   |- skyrim.py
```
`__init__.py` would get ABCs (e.g. `ModCollection` instead of `ObCollection`) that abstract over game-specific classes from the game modules. But something like this might be better:

```
bash
|- cint
   |- __init__.py
   |- game
      |- __init__.py
      |- falloutnv.py
      |- oblivion.py
      |- skyrim.py
```
That way, `__init__,py` could be further split if necessary without mixing game-specific and game-agnostic code. If the game-specific modules turn out to need further splitting as well, we can always just turn them into packages too.
Downside here is that I don't like how `game` has the same name as our already existing game handling package. Any ideas?

**Comment by Utumno** [comment]
`cgame` :P - I bet it's unique :D

Just be carefull not to open too many fronts we have py3 after all

**Comment by Infernio** [comment]
From my quick experiments, this one doesn't seem too difficult. The classes are already fairly isolated and rely on some game-agnostic base classes, so splitting is pretty doable. Will have to see how difficult designing the dynamic import will be, if it proves too hard, we'll keep the branch around and shove it on the backburner.

**Comment by GandaG** [comment]
I finished the split that Infernio started in [ganda-264](https://github.com/wrye-bash/wrye-bash/tree/ganda-264). This was only a structural split (according to import necessity). For a more in depth rework I think we should have a decision on wrye-bash/CBash#27 first so we know where to direct our efforts

**Comment by Infernio** [comment]
Closing all CBash issues as `R-rejected` (#530).
