### ISSUE TITLE
CBash memory error

### ISSUE THREAD

**Issue by Kvelja** [wrye-bash/wrye-bash#280]
(My first time reporting a bug for anything like this, so bare with me. I posted on the Bethesda forum thread and was told to post here for the CBash developers to see.)

On a 200+ Oblivion mod setup, after adding TWMP, CBash will not run to build patch due to some kind of memory error, for me specific to the heightmap Tamriel.esp as it consistently runs after disabling this specific esp. (As a user and non-developer, my guess is this is to do with the massive amount of data it's handling from a 154 MB esp.) After selecting build patch, the progress window closes in an instant and an error is returned.

```
ModFile: Error - Unable to open "Oblivion.esm" as read only via memory mapping.
LoadCollection: Error - Unknown exception


CBash encountered an error LoadCollection Check the log.
Traceback (most recent call last):
  File "bash\balt.py", line 414, in <lambda>
  File "bash\balt.py", line 1574, in _conversation_wrapper
  File "bash\basher\patcher_dialog.py", line 193, in PatchExecute
  File "bash\patcher\patch_files.py", line 471, in buildPatch
  File "bash\cint.py", line 15416, in load
  File "bash\cint.py", line 145, in NegativeIsErrorCheck
bash.cint.CBashError: 'Function returned error code -1.'
```

I receive this after testing on both Wrye Bash 306 and on 307 development, on both Python 2.7.8 and 2.7.10. Running Windows 7 64-bit. If anymore info is necessary, I'd be happy to provide.

**Comment by Sharlikran** [comment]
**In regards to the version of Python:** Although in theory 2.7.10 may work with Wrye Bash the code has not been checked against change logs.  There may be issues that don't appear during run time.

**In regards to CBash:** Not sure this can be addressed any time soon due to lack of volunteers and specifically those familiar enough with C++ to look at the CBash python code and C++ code to see where the error comes from.  The only thing I can suggest for now is that you use the python dependencies outlined in the documentation in the **Wrye Bash Advanced Readme section 2.b** and make sure they are the 32 bit versions.  This is a 32 bit app and Windows will run it properly with its internal code.

**Comment by CaiqueSell** [comment]
Do u got fix this?

**Comment by Sharlikran** [comment]
Kvelja never gave enough information and those versions are old. If you actually have the error then follow the [bug reporting form](https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Reporting-a-bug). If proper information isn't provided it will never get fixed and then there is no point asking.

**Comment by CaiqueSell** [comment]
307.Beta3 working, tnx, Sharlikran. :)

**Comment by Infernio** [comment]
CBash is gone since #530, so obsolete.
