### ISSUE TITLE
TamrielTravellersItemsNPC.esp is not being imported into the bashed patch (Version 306 and 307)

### ISSUE THREAD

**Issue by jatkinson85** [wrye-bash/wrye-bash#283]
After successful completion of the Bashed Patch I notice that [TamrielTravellersItemsNPC.esp](http://www.nexusmods.com/oblivion/mods/4387/?) is not getting imported into the bashed patch 
(there is no dot in the checkbox to denote records have been imported) despite having the following tags:

Deactivate, Delev, Filter, NoMerge, Relev

For now I've removed the Deactivate and NoMerge tags and just merged the plugin into the Bashed Patch, not even sure why those tags are there in the first place for this plugin as it only contains lvl lists.

**Comment by Sharlikran** [comment]
```
ItemNpc Fixes
- Added Correct Bash tags to these to prevent merge, this was stoping these plugin from working correctly, 
```
I don't know why the Deactivate Bash tag is there however as noted on the authors page he has added NoMerge tags to prevent you from merging them.  Please contact the author or post in Nexus community forums about plugins and bash tags.    Most Bash tags, especially for Oblivion have long since been established.  The bug tracker is for reproducible issues that impact it's operation not for questions or feedback about whether or not a plugin merges or may or may not need a bash tag.

Also the [BOSS masterlist for Oblivion](http://forums.bethsoft.com/topic/1584798-boss-for-oblivion-thread-51/page-5) is the only list currently maintained.  WrinklyNinja has removed write permissions for the other BOSS masterlists you may also find some answers there.
