### ISSUE TITLE
Add BA2 Support to Wrye Flash

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#296]
Currently there is no BA2 support and no update planed for libbsa currently used by Wrye.  So an alternative to add BA2 support is needed.

One possible resource [BA2Lib](https://github.com/digitalutopia1/BA2Lib) could be looked at but I don't know anything about the author or how well it will be maintained.

**Comment by jonwd7** [comment]
What is libbsa used for currently?  BSA to BA2 was almost no change at all if you don't have to worry about the texture-optimized BA2 format. 

I could look into updating WrinklyNinja/libbsa ... but I'd have to ask that you help answer some questions about what exactly is needed from it for your uses.   For example, I suppose FO3 and Skyrim use tes4bsa.h/.cpp?   Do you just ignore the tes3 namespace?

**Comment by Arthmoor** [comment]
I think this is being asked for to allow for recognizing the string files that Bethesda embeds inside the BA2 archives for official DLCs.

**Comment by Sharlikran** [comment]
Jonwd7 since I can't program in Python or C++ and I'm not part of that I'm unsure of everything it does.  Maybe @WrinklyNinja can answer that.  Here is what I assume so far though about what libbsa does.

### Installers Tab:

Reads the header of the BSA or BA2 file for the list of files the archive contains.

### Mods Tab:

- Reads the header of the BSA or BA2 file until it finds the strings files for the master file the archive belongs to.
- this is only my guess I have no idea if it does that -->>  Extracts the strings files to a temporary folder for use in patchers like the names patcher.

There is a chance libbsa doesn't extract files in any way.  The only reason I assume it might extract strings files is because for Skyrim I only need Skyrim_English.xxx  and Update_English.xxx strings files in the Data\Strings folder for Wyre Bash to work.  Something happens somewhere to access the strings files that are contained in the BSA files.

This is wrinkly's [libbsa](https://github.com/WrinklyNinja/libbsa) code.

>  I suppose FO3 and Skyrim use tes4bsa.h/.cpp? Do you just ignore the tes3 namespace? 

I don't know.  Fallout 3 and Fallout New Vegas don't need strings support.  I don't know how well libbsa supports FO3/FNV and I have only started adding FO3/FNV support and the support for those games isn't finished yet.  However, it would be nice if libbsa could read the BSA files for FO3/FNV so it provides the file list for the installers tab.

**Comment by WrinklyNinja** [comment]
I can't answer any questions about how Bash uses libbsa: you'd need to look to see which of the functions exposed by Bash's `libbsa.py` get used, and where. Libbsa is capable of extracting files, IIRC, but Bash may not use that.

As I said to Sharlikran, if you plan to do anything significant involving BSAs/BA2s, it's probably worth looking for a more complete/mature codebase to work off. IIRC there are a bunch of more complicated bits I never bothered supporting in libbsa, it's not great code to begin with (no tests!), and I'm not really interested in maintaining the library.

**Comment by Utumno** [comment]
@jonwd7 Sorry for the late reply - I was busy doing other stuff.

As wrinklyninja said Bash uses libsa as seen in libbsa.py - and basically the only places this libbsa is imported are for string files  ( https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/__init__.py#L2602-L2651 and  https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/__init__.py#L3900-L3934 ) and for detecting conflicts inside BSAs ( https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/__init__.py#L6781 ). I may have missed something - search for libbsa (I recomend you to use Pycharm when looking at the Bash code - see https://github.com/wrye-bash/wrye-bash/wiki/[dev]-Set-up-Pycharm-for-wrye-bash)

I also agree about libbsa with wrinklyninja - I'd rather see it gone and replaced with a minimal python implementation. Can you python ?

**Comment by WrinklyNinja** [comment]
Well, I was advising you not to reinvent the wheel. Writing a minimal
python implementation is pretty much the opposite of what I suggested.

**Comment by matortheeternal** [comment]
There's a lot of BSA/BA2 related stuff out there, it'd be nice if we could have a single source project to maintain.  That source project could maintain wrappers for various languages, a suite of tests, and all necesssary build configurations.  It could also offer both managed and unmanaged C++ options (CLI and not CLI).

**Comment by Sharlikran** [comment]
I'm burning my food trying to come up with what to say.  But I think I will start with this.  Utumno is the only volunteer working on this project.  He has been working on the project for over a year now.  I'm not much help because I can only port xEdit records to Wrye.  I can't update core programming.  

While the Wrye project isn't dead once Utumno is no longer working on it, all supporters, users and fans will have to wait for a new volunteer to step up.  How long will that take?  Months, years?  So short term, If I can find volunteers to take some of the stress and work load off of Utumno then I will be very eager to utilize that help and very grateful as well.  

I know Utumno has a lot on his plate and is deep into refactoring with limited spare time.  Even if I only get two DLL files and Utumno has to change the Python code that's still less work for him and very helpful.

------------------------------------

@WrinklyNinja thanks for clarifying whether or not libbsa can extract files.  I appreciate it.

------------------------------------

@Utumno the links to the code are great but we don't know if Jonwd understands Python.  I know you have been doing all the work for a while now but you are probably better suited to answer the question then Jonwd trying to look through the Python code.  When you were looking at the code that you linked, did you notice what Wrye was doing in relation to the strings files?  Does it look like Wrye is extracting strings files somewhere like to a temp folder?

------------------------------------

@jonwd7 When I started the ticket I didn't have any short term temporary fix.  I brought you in, since you wrote BAE.  As a possible long term fix does BAE have a DLL that could be used with a Python wrapper?  If not I wouldn't ask you to make one there are probably other solutions.

As a short term fix, are you still interested in taking a look at libbsa and adding BA2 support?  I know you asked what libbsa does and what it is used for.  It looks like there is good confirmation that libbsa both extracts files if needed and reads the header of the archives for the list of files the archive contains.  The short answer seems to be that libbsa would need to do both for BA2 support.  

Now wrinkly has said his dll doesn't have the best code and wasn't tested well.  However, if the BA2 support had minimal changes could you use the existing code as an example to implement the BA2 support?  I don't want to ask you to do something you don't feel comfortable doing however, I'm basically looking for a cut and paste kind of job.  Even though Wrinkly feels his libbsa isn't his best work it does the trick for what Wrye Needs.  As a short term fix it's doesn't have to be glamorous.  We have plenty of testers so that's not going to be an issue.

Can you help with that?

**Comment by jonwd7** [comment]
@Sharlikran  I think the actual archive code in BAE has too many dependencies on Qt to be useful as a DLL.  NifSkope uses Qt and most of the BAE code is just from NifSkope (literally everything but the FO4 changes), so I kept the Qt dependency and also wrote the BAE UI with Qt. 

If I could strip out all the dependencies, compile it separately into DLL, then BAE, NifSkope, etc. could use it as a DLL.  Except that still leaves how terribly it's written.

Basically, the code used in BAE and NifSkope wasn't written to be an actual library and uses shared dependencies with other stuff it's used in.  At least libbsa was written to act as a library so it's already about 20 steps ahead.  I know WrinklyNinja doesn't think it's worth updating, but I feel it's definitely the best candidate.   You already use libbsa API, so the only changes would hopefully have to be on libbsa's end.

I'll try to familiarize myself with the libbsa code but at least for the functions you use it doesn't seem too hard.  I see the libbsa API also has Save() and such, and I have no plans on trying to write BA2 files and I'd personally like to leave that unimplemented.  For GNRL header BA2s, maybe, but there are also DX10 header texture BA2s which I really don't want to be responsible for writing.

One thing I'm not sure of at the moment, for "detecting conflicts" do you just check presence or also checksum?  And I assume you need to do this for texture BA2s as well?  The issue is that texture BA2s aren't actual DDS files.  Depending on the settings when making a texture BA2, the file actually gets treated as multiple files broken up into mipmap chunks.   I'm not sure offhand if there is any kind of file checksum stored for all the chunks together, but I'm guessing not.  I guess I could checksum the first chunk only however.

**Comment by Sharlikran** [comment]
@jonwd7 Thanks for explaining that.  I won't worry about getting BAE to work with Wrye then.  There is still BA2Lib and there could be other BA2 libraries.  We just have to keep looking.

>  I have no plans on trying to write BA2 files and I'd personally like to leave that unimplemented.

You're kind enough to take a look at it so by all means, leave that part alone.  I don't think Wrye saves BSA files anyway and there are plenty of archive tools.

> One thing I'm not sure of at the moment, for "detecting conflicts" do you just check presence or also checksum?

@WrinklyNinja Didn't you write the Python code to use libbsa initially?  Do you remember off the top of your head if it used both?  @Utumno If Wrinkly doesn't remember, can you look at the Python code to help out with this?  

I'm going to say presence and checksum.  When Wrye looks at loose files I'm pretty sure it looks at both because there are tabs for files that are the same and files that are mismatched.  You couldn't do that without a checksum.

>  For GNRL header BA2s, maybe, but there are also DX10 header texture BA2s which I really don't want to be responsible for writing... The issue is that texture BA2s aren't actual DDS files. Depending on the settings when making a texture BA2, the file actually gets treated as multiple files broken up into mipmap chunks. I'm not sure offhand if there is any kind of file checksum stored for all the chunks together, but I'm guessing not. I guess I could checksum the first chunk only however.

If conflicts can work for only general BA2 files that's fine.  Users may say Skyrim had that but Fallout 4 doesn't however, we can explain why.

What I would like to ask is that you keep it in mind for a later date.  The reason is, if Bethesda makes an official tool that can extract files from BA2 files and create BA2 files then authors like yourself won't need to develop 3rd party tools like BAE.  On the other hand if Bethesda's official tool fall short of user expectations and you have to create BA2 texture files then at least consider adding that to libbsa if we haven't found a replacement by that time.

**Comment by WrinklyNinja** [comment]
> I am pretty new to all this, but it just seems like a mess to have so many separate projects.

Yes, it is, and part of the reason is that none of us really know what else is out there. To that end, you've inspired me to start [this list of modding libraries/tools](https://github.com/WrinklyNinja/es-modding-tools). It would be great if everyone forked it to make PRs adding anything that's missing to the list, and shared it around!

> At least libbsa was written to act as a library so it's already about 20 steps ahead. I know WrinklyNinja doesn't think it's worth updating, but I feel it's definitely the best candidate.

In that case I'll take a look at the code tonight and hopefully at least update the CMake build script to be easier to work with, more like the latest LOOT/libloadorder builds. Maybe also add some tests for the current functionality, but no promises.

> One thing I'm not sure of at the moment, for "detecting conflicts" do you just check presence or also checksum?

It's just by file path, IIRC.

**Comment by matortheeternal** [comment]
@WrinklyNinja Awesome, that's really cool.  Good call and nice initiative!  :+1:

**Comment by WrinklyNinja** [comment]
I've made a bunch of updates to libbsa over the past 24 hours, simplifying the build system, using C++11 to remove some Boost dependencies, removing unused code and unimplemented functions, adding the Google Test framework (there are only a few empty tests so far), hooking it up to Travis CI, and generally tidying things up.

I'll get around to adding some tests, but if anyone wants to add BA2 support to libbsa, they should now find it easier to get started.

**Comment by Sharlikran** [comment]
@jonwd7 I wonder if you would be willing to take a look at libbsa again to add BA2 support for Fallout 4?

**Comment by jonwd7** [comment]
@Sharlikran  I was actually in the process of trying to just make my own, but then I took a break for 6 weeks or so..

As far as new BSA formats...  the compression on the files in the new BSAs for Skyrim SE are very weird.  I messaged @ianpatt at beth.net and also I've been talking to @Orvid on Skype, but currently I don't even know how to decompress the new files. 

If I don't make progress with my own lib I will try to revisit updating libbsa.  My issue mainly was the remaining dependencies on Boost, which I think could be replaced with C++14/17 (e.g. std::filesystem).  But since BA2s are so different I would be adding so much to libbsa that I still want to try starting from scratch first.

In the process of rigorously understanding BSA/BA2, I made 010 Editor templates for parsing the archives.  They also verify hashes and do other data integrity checks.  This way I will have something to verify archives created with the lib.

If anyone has 010 and wants to use them I just uploaded them here:  https://github.com/jonwd7/0x6e6966746f6f6c73

**Comment by ianpatt** [comment]
Try https://github.com/lz4/lz4 for compression. I haven't verified it yet, but that's what appears to be.

**Comment by Orvid** [comment]
Certainly possible. If I had a binary I could tell for certain what it is, but I don't currently :( Is LZ4 byte-based or bit-based? Whatever's being used for SE is definitely byte-based.

**Comment by jonwd7** [comment]
@ianpatt You're right.  We had just been looking at LZ4 but I hadn't looked for the magic number yet.  I remembered the 17 bytes starting with `E0 55` so I thought it wasn't going to be it, but sure enough the magic number is there, just later.   `E0 55 01 00 04 22 4D 18`.

**Comment by Utumno** [comment]
I am interested in having a pure python API for this - I can reverse engineer the C++ code when ready (please add comments) but wouldn't it be easier to _begin_ in python for easy prototyping ?

**Comment by ousnius** [comment]
Thing is we already all have our own code bases for BSA related things, so it might be easier for us to dump the stuff in there and with some luck it will work pretty quickly and pretty well.

**Comment by Utumno** [comment]
Anyone knows how are the filenames/folder names encoded in the bsas/ba2 ?

**Comment by ousnius** [comment]
Files are the same, folders are:
uint64 hash;
uint32 fileCount;
uint32 unknown;
uint64 offset;

**Comment by Arthmoor** [comment]
Compressed files are using LZ4 though instead of whatever they had before.
That shouldn't be an issue though if all you're after is supporting strings
inside the interface BSA file since that file is not compressed.

**Comment by Utumno** [comment]
No no I mean the filenames and folder names are encoded in cp1252 ? Or ascii? Or ... ?

**Comment by Arthmoor** [comment]
Oh, that I don't know. Sorry.

**Comment by WrinklyNinja** [comment]
Cp1252, I think, though it's been a while since I last looked.

**Comment by Utumno** [comment]
@jonwd7 @WrinklyNinja @ousnius: what would certainly help is a repository with various BSA/BA2 test cases (maybe hand crafted). For instance most (all) implementations I've skimmed through take for granted that the archiveFlags^1 is true - have you come across any bsas in the wild that have this bit unset ?

The matter of encoding also I think should be settled.

**Comment by jonwd7** [comment]
@Utumno  .. @ousnius and I already tested some things.  When hashing, it strips anything that's not a valid ASCII (non-extended) character from the filename.  You can see this here:  https://github.com/jonwd7/0x6e6966746f6f6c73/blob/master/ba2/BSCRC32.bt#L97 accomplished via the rejection of negative bytes, i.e. 128-255 as unsigned bytes.

My 010 templates, which I see you've starred, have already validated this for BA2s by verifying the hashes of non-ASCII filenames.   Though I haven't thought about checking this for BSAs until now.   The BA2 does store the full text e.g. `testßöäüß.txt` but when hashing it's essentially `test` (plus it adds the extension to the end of the hash which is called the "Resource ID") .  This means that you can have filename hash collisions if the non-ASCII character stripping results in the same string and the files have the same extension.

However IIRC, this is mostly pointless as the CK does something completely different with non-ASCII filenames.  It tries to convert them, which results in a garbage string stored as the filepath.  What generally happens when you attempt to create the archive is that it says the file can't be found because it's looking for the garbage string and you basically have to take random characters out of the filename until the CK can find the file. 

>For instance most (all) implementations I've skimmed through take for granted that the archiveFlags^1 is true

I assume you mean `archiveFlags & 1` (and also 2) and yes, it must be true or presumably the engine can't read the BSA.  If you leave Retain Dir/File Names unchecked in Archive.exe it still sets the bits.  So we have no way to officially generate a BSA with that structure and thus we can't know how it's supposed to be laid out.   I could take a guess at the layout without those bits and see if the engine would read it, but that's not really an edge case worth looking into.

**Comment by Sharlikran** [comment]
@Utumno @jonwd7 obviously knows more then me, but do you have his basic information on the format of the files?  Despite what Wrinkly has already said in regards to a Python implementation, I guess libbsa only ever read the list of files so that's all the Python code would have to do.  Without extracting any files from the BSA/BA2 you need to be able to 1) read the list of files for the installers tab to show conflicts with other files both loose files and files in other BSA/BA2 files and 2) Read the strings files from within the BSA/BA2.

Without the strings files Wrye will not build a bash patch even if the option is activated.  Even SSEEdit is effected in that strings are currently not shown and instead the 32 bit pointer to the strings file is displayed.  Without the ability to read the strings files they have to be extracted and placed as loose files in the Data folder in a subfolder named Strings.  i.e. .\Data\Strings

**Comment by Utumno** [comment]
@jonwd7:

> When hashing, it strips anything that's not a valid ASCII (non-extended)

The ba2 or bsa ? I guess ba2 - in which case what do bsas do ?

> My 010 templates, which I see you've starred, have already validated this for BA2s

Haha - I did not quite get that they were actually valid c - I just loaded them in the editor and they indeed helped me a lot deciphering the bsa format for oblivion

> archiveFlags & 1

Yep, sorry that's what I meant. My point is not so much we should care for these edge cases as that we should have a clear specification somewhere taht says what we care for and what not. And this is best to come in the form of a repository with test bsas and a nice readme. I am sure @WrinklyNinja will agree with me that we need some unit tests there - but instead of everyone having its own test files let's at least have a common test repository. Anyone can set this up ?

>  I guess libbsa only ever read the list of files 

Can write them too - just unused in Bash. Alright Sharl we know what must be done - who's gonna code it is the question :P

**Comment by Utumno** [comment]
Bsa/ba2 read support in Bash - for the first time in Bash history with tests:

https://github.com/wrye-bash/wrye-bash/blob/utumno-wip/Mopy/bash/bosh/bsa_files.py
https://github.com/wrye-bash/test_bash

I need a rundown of where is compression used in the various games in case I am able to throw that in - cause apparently we do need more that reading the files - ModFile#load unpacks the string files (not sure why ?). Anyone ?

Good news is zlib is in python  std - bad news lz4 is not

Plus we need _test resources_. Can anyone hash up some small bsas/ba2s for each game ? Be aware that there is at least one snag - unaccurate folder names block sizes - see https://github.com/jonwd7/bae/issues/1 - so we do need to test that too, and who knows what else.

**Comment by jonwd7** [comment]
As far as I can tell, you don't even need the `Folder Name Length` for anything.  Note:  You called it a block size, but the folder name length is not its own contiguous block of data.  It's the sum of the size of each folder string at the start of each group of file records (organized by their folder), minus the number of folders (to subtract the length byte for each sized string).

Or in other words the sum of each size indicated here: 
![foldernamelengths](https://cloud.githubusercontent.com/assets/170077/20033887/3554b0f8-a382-11e6-800b-42608248d242.png)

_(Note: The filename strings in the Value column are not actually stored there, but pulled elsewhere from the file for display purposes. The **Path** string for the folder IS stored there.)_

My 010 template doesn't even use `Folder Name Length` for anything.  Though I suppose to be rigorous, my template should be calculating its own folder name length and comparing it to the one in the header, so that it can warn of such problems. :)

**Comment by Utumno** [comment]
>  Note: You called it a block size, but the folder name length is not its own contiguous block of data

Yep sorry I know.

> My 010 template doesn't even use Folder Name Length for anything

Yep that's probably why it parses the bsas I reported in  jonwd7/bae#1

Btw those templates are magic for me - black magic

----


Could you give me rundown of the compression methods used per game ? Are only the file data compressed and are those compressed per file ?

----

> When hashing, it strips anything that's not a valid ASCII (non-extended) character from the filename. You can see this here: https://github.com/jonwd7/0x6e6966746f6f6c73/blob/master/ba2/BSCRC32.bt#L97 accomplished via the rejection of negative bytes, i.e. 128-255 as unsigned bytes.
> ...
> However IIRC, this is mostly pointless as the CK does something completely different with non-ASCII filenames.

So basically _only ascii filenames_ are supported ?

All this points again to the need to have a common set of bsas all libraries should test again - please do not overlook my repeated claim. My testing code uses vanilla bsas/ba2s and some modding ones but I can't of course publish the bsas so it's of limited use. We need to set up a (lightweight) repo with resources that exhibit all those issues (for the moment, folder names size, missing flag bits 1,2 and encoding) and have our code test against those.

Anyone volunteer to set up those bsas ?

**Comment by jonwd7** [comment]
>So basically only ascii filenames are supported ?
No they do, but the non-ascii characters are not counted as part of the hash in BA2s.  Meaning testßöäüß.txt is the same as test.txt when it comes to their "Resource ID" (the filename hash + the first 3 extension characters).  If you were to try to pack testßöäüß.txt and test.txt with Archive2 it would warn you of the collision.

However, I recently updated my templates for BSAs, because my hash algorithm for verification purposes was not correct when paths used extended ASCII characters:  https://github.com/jonwd7/0x6e6966746f6f6c73/commit/2a0ace288e5e13ec5e8ae8d3b4c0f3ff25ac1efe#diff-d4bd2d1de2fbabe383bfb1275507464bL237

BSAs *do* include the extended ASCII characters in the hash, by casting each letter to unsigned char.  BTW I didn't cast the file extension chars on L252 and I probably should have, but realistically no extension is actually extended ASCII.

>Could you give me rundown of the compression methods used per game ? Are only the file data compressed and are those compressed per file ?

Everything before SSE is zlib.  The compression is only for the file data, but in Oblivion the compression toggle is part of the filesize in the file record.  In later games the compression toggle is in the BSA header and applies to all files.

And actually thinking back on it I think my size calculation for Oblivion file data is backwards in the templates.  `size & 0xC0000000` being greater than 0 tells you that the file is compressed.  To get the actual size it's `size & 0x3FFFFFFF` which is why the individual filesize limit is ~1GB.  Even though the compression toggle is global in later games, I believe the filesize may still get masked by 0x3FFFFFFF. 

> Anyone volunteer to set up those bsas ?

I'm not overlooking it BTW, it's that I don't consider it very high priority right now.  :)  I have my own local test BSAs, but they are not ideal and not fit for a public repo.  I'm also not particularly interested in Oblivion BSAs at this point, and don't have any kind of official packer to even make test BSAs for that version.

**Comment by jonwd7** [comment]
Addendum:  After looking at it quickly,  Oblivion also supports the global compressed flag, so I have no idea where the compressed flag on each file record gets used.  It's possible that maybe all the games support the global flag being off and certain individual files having compression toggled on.

**Comment by Utumno** [comment]
Thanks a lot @jonwd7 - I will come back for more. What puzzled me among others is we read in both [skyrim](http://www.uesp.net/wiki/Tes5Mod:Archive_File_Format) and [oblivion](http://www.uesp.net/wiki/Tes4Mod:BSA_File_Format#File_Record) pages:

> If the (1<<30) bit is set in the size:
> 
>     If files are default compressed, this file is not compressed.
>     If files are default not compressed, this file is compressed.

where "default compressed" is the archive flags bit 4

**Comment by Utumno** [comment]
Interlude - turns out that loading the bsas blows memory use by ~30 mbytes - I will have to see if I can reduce this

**Comment by jonwd7** [comment]
Yeah.. It's something I have recently thought of ways to address after profiling allocations in NifSkope during startup.  It loads all the texture BSA info for when NIFs get opened and need texture lookups.

The BSA code in NifSkope (and by extension BAE) is actually pretty bad.  I'm eventually going to replace it. 

In the meantime I realized that all I need for my texture loading for example is the texture filepath for the hash key, and the BSA pointer and the offset to the file record stored in a pair with the key.  So all I really need in memory is the string hash, the BSA pointer, and a 64-bit int for the file record offset.   Currently the BSA code loads not only every file record into memory but every folder record and the entire hierarchy as well.  Even though with texture lookups I only need a flat list.

Of course I'm not sure how your uses differ from mine.  But if you're loading the full file and folder records you may want to start there.

**Comment by Utumno** [comment]
Well - I basically only load the asset filenames ! That's crazy, and I will most probably leave it be, I can afford some memory for the performance. In general python memory profiling is an arcane subject and I have the BAIN tab that needs couple hundred megabytes and the leak in the python patcher which is another triple hundred - never really managed to find a tool for tracking those. But memory performance is for 308, for now it's speed and that goes well.

Still jeez - I have a load_light method I use, happy I wrote that, I wonder what full load would cost me - edit: actually 70 more megabytes when I use full load (all the file/folder records) - and I use the `__slots__` optimization (I used it for design reasons not performance but it should help)

----

What about the "compression toggle" - have you seen that used ? Is the (1<<30) bit set equivalent to size & 0xC0000000 being positive ? I miss something here

Re: tests - I am not referring to oblivion specifically - actually  I'd like all the games tested. Anyway volunteers needed, but it would really help to have a set of reference uncopyrighted bsas

**Comment by Utumno** [comment]
@wrye-bash/bashers: I found (unused) code in Bash for writing Archive Invalidation.txt - I guess this is safe to be removed (we won't need to write that file ever - right ?)

**Comment by Arthmoor** [comment]
Assuming you're asking specifically about Fallout 4 for that invalidation stuff, yes. You can get rid of it. The game doesn't use it. For the record, neither do Skyrim or SSE.

**Comment by Utumno** [comment]
Thanks @Arthmoor but nope I am asking for Oblivion also - the code is unused we use bsa redirection IIUC - but could this be used somehow (in Oblivion) ?

**Comment by Arthmoor** [comment]
Technically archiveinvalidation.txt can still be used in Oblivion, and if you want the codebase to support Morrowind at some point, it can use it too.

OB currently has alternative solutions. I don't know about MW though. FO3, NV, Skyrim, FO4, and SSE don't use it at all though.

**Comment by Utumno** [comment]
Thanks @Arthmoor - well since it's unused (we use bsa redirection as far as I can see) I will bin it in a clean commit - we can readd it if needed. Cleaning up the internal bsa APIs

**Comment by Arthmoor** [comment]
Sounds good to me, assuming the main Bash is not planned to support Morrowind at some point down the line.

**Comment by Utumno** [comment]
> the main Bash is not planned to support Morrowind at some point down the line.

If you find a volunteer I could show him around :P

**Comment by Utumno** [comment]
Starting to write extraction routines. Questions:

- is finally the compression flags the same @jonwd7 for all games apart fallout4 ? That is the global compression flag and individual file records compression flags that toggle global ? I see you edited the templates so I guess yes.
- Re: this compression toggle. You are using `0xC0000000` while libbsa is using `0x40000000`. So what is the significance of bit 31 (counting from 0) ? libbsa again ignores this when masking the file size (`^0x40000000`) while you zero it (`&0x3fffffff`) (I got them xor right this time!)
- I also see some special treatment for skyrim se bsas: https://github.com/jonwd7/bae/blob/master/src/bsa.cpp#L446-L449. Why is this ?
- has archiveFlags bit 9 the same meaning in all those games - namely _embed filenames in file data_ ? The docs for oblivion bsas mark it as unknown: http://www.uesp.net/wiki/Tes4Mod:BSA_File_Format#Header - but then it contradicts itself by using this bit to decide if filenames are embedded: http://www.uesp.net/wiki/Tes4Mod:BSA_File_Format#Compressed_File_block. You only seem to set it to true for post oblivion however: https://github.com/jonwd7/bae/blob/master/src/bsa.cpp#L254-L256
- Bonus: do bsas in the wild actually ever have this bit off ?

Thanks!

**Comment by jonwd7** [comment]
I haven't edited the templates fully yet.  Since nothing I can find uses this compression toggle it's kind of hard to verify what you were saying about it basically meaning the opposite of the global flag.  (If global compressed, flag means uncompressed) 

Although my templates don't actually care if the data is compressed or not,  I do put text in the comments if that flag is set, so that's the only thing that's "wrong" with the templates right now.

Re:  `0xC0000000` vs `0x40000000`  ... are you sure `^0x40000000`  is where libbsa is deciding the filesize?  Because I believe that's wrong.  `0x40000000` is the flag for compression alone it seems, and `0xC0000000` is "all flags".   To get the correct filesize it's `size & (~0xC0000000)`,  meaning you flip the "all flags" number and then and it, and `(~0xC0000000)` = `0x3FFFFFFF`. 

This assessment is via BSAOpt:  https://github.com/Ethatron/bsaopt/blob/master/io/bsa.C#L115  https://github.com/Ethatron/bsaopt/blob/master/io/bsa.C#L1324

And we do know for sure that the max individual filesize is 1GB - 1 (0x3FFFFFFF) because the bit after that is the compression toggle.

>Bonus: do bsas in the wild actually ever have this bit off ?

If you're talking about bit 9, then yes.  It's actually very seldomly used.  It's unnecessary as bits 0 and 1 are always on.  (Retain filenames and dir names).   And as I said earlier I don't have the Oblivion BSA packer so I can't really verify any of that.

**Comment by Utumno** [comment]
Re: toggle - so your final answer is maybe ? :)

However you are using it as a toggle, so does libbsa so I will probably have to do the same

However if someone could just decompress some textures repack the bsa with the toggle on and see how does this perform in game (are the textures seen ?) then it would settle the matter - my python code is far from packing/decompressing etc

> are you sure ^0x40000000 is where libbsa is deciding the filesize? 

I guess so - for instance : https://github.com/WrinklyNinja/libbsa/blob/3559ef1d915b84c27434506660f2a4e7e1634e75/src/api/tes4bsa.cpp#L342-L343 where [FILE_INVERT_COMPRESSED](https://github.com/WrinklyNinja/libbsa/blob/3559ef1d915b84c27434506660f2a4e7e1634e75/src/api/tes4bsa.h#L56)

> So what is the significance of bit 31 (counting from 0) ?

If `0xC0000000` is all flags what's the significance of the other one ? I see you assume it's zero for BSAs - actually you use it to decide if it's a BSA or a BA2: https://github.com/jonwd7/bae/blob/master/src/bsa.cpp#L453 - my hex is a bit rusty but I guess `file->sizeFlags > 0` means basically highest order bit is 0. If it's always 0 then that's why libbsa is using `^0x40000000` (although I'll go and correct it in my code)

> If you're talking about bit 9, then yes.

So its meaning for oblivion will escape us - if you do find an _Oblivion_ bsa that's using it then please let me know - it does make a difference if those filenames are embedded - for the rest of the games I will go with you and the wiki and assume this bit does mean embedded filenames

Thanks!

**Comment by matortheeternal** [comment]
Just an FYI, I have [a PR into libbsa](https://github.com/WrinklyNinja/libbsa/pull/6) with SSE BSA support open right now.  (I don't think decompression is working properly because I haven't added LZ4 to libbsa, but getting the folder/file table is working)

Also, I was notified about [this library](https://github.com/AlexxEG/BSA_Browser) having support for BSA and BA2 files in all formats.

**Comment by ousnius** [comment]
I don't know why you're still looking for more references, we already had BA2 and the new BSA format in out B.A.E. and Outfit Studio repositories almost since release of each format. There's nothing (relevant) that's still unknown about it.

**Comment by Utumno** [comment]
What would be really worth your time would be to set up a reference BSA _testing_ repository with hand made, copyright free BSAs/BA2s, complete with indexes and extracted files, so we could have a common reference for testing.

**Comment by matortheeternal** [comment]
@Utumno WrinklyNinja has that set up [here](https://github.com/WrinklyNinja/testing-plugins).  It may not meet all of your requirements, but I image you could make PRs to expand the repository as needed.

**Comment by Utumno** [comment]
@jonwd7 (or any one that might know) - tiny question: for GNRL ba2s does `packed_size == 0` mean the file is uncompressed ? That's the only thing I need to test ?

**Comment by jonwd7** [comment]
I believe so, yes.

**Comment by Utumno** [comment]
Bash is now able to extract uncompressed string files for all games it supports. Next step would be to support extraction for compressed bsas so we could feature a pretty much complete bsa tab ( #233 ).

Please have a look at https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh/bsa_files.py

I am rather satisfied with my design - it's easily extendible for new games and I find the code readable enough. However there may be bugs in there, design or otherwise, so feedback much appreciated.

Keep posting in this issue - I am just closing as it served its purpose as an enhancement

Thanks everybody!
