### ISSUE TITLE
Effect data for winning record is not copied.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#306]
This one is similar to Issue #305 in that the winning record data is not copied with a mod to merge in between.

The effect data should get pulled in along with the graphics change.

https://i.imgur.com/pqTWAIk.jpg

To reproduce, Mark WiningKeywordModToMerge.esp as mergeable. Set the load order to have WinningRecordKeyword.esp load before it. Then process the Bashed Patch and let it merge the second WITHOUT merging the first.

[WinningKeywordRecordOther.zip](https://github.com/wrye-bash/wrye-bash/files/264373/WinningKeywordRecordOther.zip)

**Comment by Arthmoor** [comment]
As of 307.201610020028 this issue is still present.

**Comment by Infernio** [comment]
The linked plugins do not seem to be related to this issue? I manually modified them to reproduce the screenshot:

![ENIT-Conflict](https://user-images.githubusercontent.com/2845240/68551614-10237080-040f-11ea-9fac-e2891136e355.png)

If that is what you mean, then it's expected behavior. See the wiki page [on PBash's patching procedure](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-PBash-Patching-Procedure):
> 8\. This is where the BP merges mods, resolves aliases, applies Filter and IIM tags, etc.
> ....
> 11\. Each patcher uses the information it has gathered in the previous stage to do its importing, merging, tweaking, whatever. They operate on the records that were placed in the BP in step 7 here - 
> meaning that different patcher's changes merge together automatically! That's the reason patchers add every record they could patch to the BP.

This means that a merged mod's records will *completely override records from any mods before it*, unless you add tags to the mods before it so that they can be picked up after the merging.

**Comment by Infernio** [comment]
Please comment / reopen if this can be reproduced again.
