### ISSUE TITLE
Update 7zip DLL code to fix vulnerability

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#313]
Since Bash uses the 7zip library for BAIN, this may be of importance: http://forums.theregister.co.uk/forum/1/2016/05/12/popular_zip_tool_7zip_pwned_pain_flows_to_top_security_software_tools/

Not sure where the actual downloads for that are, but it would be prudent to have this ready for 307.

**Comment by Utumno** [comment]
Thanks for posting an issue - I was trying to figure out if this is really important for us - will have a more thorough look.

**Comment by m0lz** [comment]
Wrye Bash just includes the .dll and .exe from 7zip ( Mopy \ Bash \ Compiled \ 7z.exe and 7z.dll )

7zip is available for download here http://www.7-zip.org/

I would consider this important, if Wrye Bash uses its own installed version instead of any version a user will have installed.

But even if the user installed version is used, just for confidence in the project any potential security risk really ought to be resolved.

**Comment by Utumno** [comment]
Yep seems I have to include this in the beta - happily it affects UDF or HFS+ archives which are not used by Bash

**Comment by Utumno** [comment]
Some links:

Severe 7-Zip vulnerabilities cause top security, software tools patch panic | ZDNet
http://www.zdnet.com/article/severe-7-zip-vulnerabilities-cause-top-security-software-tools-patch-panic/
Cisco Talos Blog: Multiple 7-Zip Vulnerabilities Discovered by Talos
http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

And:
http://www.7-zip.org/history.txt
