### ISSUE TITLE
Wrye Bash v306 (minor inconsistency post patch building between USKP and USLEEP)

### ISSUE THREAD

**Issue by neoh4x0r** [wrye-bash/wrye-bash#325]
This is just a minor inconsistency in the text of pop-up window you get after rebuilding the
bashed patch.

I'm using Wrye Bash v306 (downloaded from the nexus)

When rebuilding the bashed patch I get references, in the
results dialog, that pertain to USKP rather than USLEEP.

I have verified that USLEEP is installed (and Wrye bash confirms this)

But in the dialog (after building) it will show 

"Unofficial Skyrim Patch.esp [ADR]"

rather than 

"Unofficial Skyrim Legendary Edition Patch.esp [ADR]"

Again this is only minor  has no real impact on anything -- it's just inconsistent.

**Comment by Utumno** [comment]
Please try the 307 betas from here: https://www.dropbox.com/sh/7b5ily482re0khs/AAD3vAWMVJNIpuS30tsdVte5a?dl=0

Do you have this Unofficial Skyrim Legendary Edition Patch.esp - or is it renamed to Unofficial Skyrim Patch.esp ?

**Comment by neoh4x0r** [comment]
Yes I have "Unofficial Skyrim Legendary Edition Patch.esp" (USLEEP) installed
and I do not have any file named: "Unofficial Skyrim Patch.esp"

However, I cannot test beta 307 -- I am running under wine on linux and I get this error:
5:27:27 PM: Debug: src/helpers.cpp(140): 'CreateActCtx' failed with error 0x00000103 (no more data available.).

**Comment by Arthmoor** [comment]
Can you show us a screenshot of the results output? There are a lot of reference names that begin with USKP as the letters when used in editor IDs and such. That's expected. We didn't bother changing those because it would have caused script property names to change too and would have made upgrades impossible.

**Comment by neoh4x0r** [comment]
@Arthmoor yes I have uploaded from screenshots to dropbox
**The leveled list plugins auto-selected by wrye bash:**
https://dl.dropboxusercontent.com/u/104054522/wrye_bash/uksp_usleep_issue_scrnshot/0%20-leveled_list_entries.png

**The results dialog (showing: USKP, UDP, UDBP -- instead of USLEEP) [these are repeated through out the rest of the dialog]**
https://dl.dropboxusercontent.com/u/104054522/wrye_bash/uksp_usleep_issue_scrnshot/1%20-results_dialog.png

**Directory Listing of Unofficial patches installed:**
https://dl.dropboxusercontent.com/u/104054522/wrye_bash/uksp_usleep_issue_scrnshot/2-%20file_list.png

**Comment by Arthmoor** [comment]
No idea how that's even possible if the files are not physically installed. They're not sitting around in your BAIN installers either are they?

In any case, I suspect @Utumno will want to close this if it isn't happening in 307. Very strange either way. Can't say I've seen it before.

**Comment by neoh4x0r** [comment]
@Arthmoor What makes it even more stranger is the fact that after running 307 -- now all of a sudden 306 shows the correct information.

I think 307 must have corrected some records in the bashed patch (from 305/306) -- and that is why 306  works now (it does not see the removed records anymore)

**Comment by neoh4x0r** [comment]
@Arthmoor What makes it even stranger is the fact that after running 307 -- now all of a sudden 306 shows the correct information.

I think 307 must have cleaned up something that was confusing 306.

The results dialog (as now seen in 306 [after running 307])
https://dl.dropboxusercontent.com/u/104054522/wrye_bash/uksp_usleep_issue_scrnshot/3-%20306_results_dialog_after_running_307.png

**Comment by Utumno** [comment]
Thanks @Arthmoor - appreciated!

@neoh4x0r: Probably some stale information - glad my little pet cleaned it up - since you restored settings it wasn't in the settings (_if_ the settings were correctly restored - this code needs some love, try restoring them manually). There was a lot of refactoring around the patcher dialog so.... Please keep using 307 and report any issues you encounter in the forums http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/ - you have an eye for details it seems :)

Always post the full BashBugDump.log please since you manage to produce it

You are not on wine are you ?

-----

>  Also on a side note the 307 beta does not like symlinks for the game folder.

That's bad - could you report it to @WrinklyNinja ? I updated the loot dll - it's not Bash - it's the loot dll that changed behavior.

**Comment by WrinklyNinja** [comment]
@neoh4x0r: Please describe how you created your symlink as a comment in loot/loot#645, so that I can replicate your setup for testing.

**Comment by neoh4x0r** [comment]
@Utumno Yes I am using wine 1.8.4
@WrinklyNinja I will add a comment in the loot issue shortly

**Comment by Utumno** [comment]
@neoh4x0r: interesting info - https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug ;)

Anyway closing this for now as worksforme (not invalid though) as indeed 307 beta is shortly out.

Any and every info on Wine setup/bugs is precious - post at relevant issues: https://github.com/wrye-bash/wrye-bash/labels/wine - have a look also here: https://github.com/wrye-bash/wrye-bash/wiki/[dev]-Running-Wrye-Bash-on-WINE-(Arch-Linux) (I guess you already did)

I do hope wine 1.8.4 fixes some of the issues - the catch all issue is #240 - post there to discuss before opening a dedicated issue

**Comment by WrinklyNinja** [comment]
Posting this here since it seems like the most appropriate place...

@Utumno: A Python wrapper snapshot build that includes this fix is [now available](https://bintray.com/wrinklyninja/loot/loot-api-python/14e671f_master#files). I've also added automated Linux builds for the wrapper, as proof of cross-platform support and in case they might be useful in the future.

I'll probably take a look later this week at updating the NSIS installer to handle the MSVC runtime and have a poke around to see what needs changing to switch to the LOOT API python wrapper. I am planning to rebuild my PC though, so it's all dependent on how smoothly that goes. 🍀

**Comment by Utumno** [comment]
Thanks @WrinklyNinja - good luck with your pc, wish me luck with my git corruption (git gc on laptop dropbox sync on desktop boom)

Really have no time to look at this but if loot 10 is out soon and since it changes the masterlist format then should be bundled with Bash - no use bundling 9.2
