### ISSUE TITLE
Replace wtxt with HTML

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#33]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/237/)

@WrinklyNinja: Wtxt is, as far as I am concerned, a horrible mutant half-breed of HTML and Wiki syntax that Bash uses to display generated formatted text. It's unique to Bash (ie. no tutorials or documentation on the internet) and AFAICT Bash reads in files that are in Wtxt, then converts them to HTML to display in wxWidget's HTML display classes. Why not just write the files in HTML to begin with? Is that not easier than inventing your own language, writing files in that, then writing a converter?
Anyway, I think it would be excellent if Bash got rid of Wtxt and just switched to having its Wtxt files in HTML and generating HTML content straight. One less thing for people unfamiliar with Bash to flounder at.

**Comment by Infernio** [comment]
Not happening. HTML is utterly unsuitable for the things we do with wtxt, since it'd be *much* harder to generate it (e.g. in the patcher logs, which are all wtxt). Markdown would be a more likely alternative, but I'd rather put effort into improving wtxt documentation than into rewriting every single wtxt usage in the code.

**Comment by Utumno** [comment]
Actually there is a `codebox` static in there that should be refactored to be less of a global hack, have a look if you ever get round to it ( search for `bolt.codebox = WryeParser.codebox`)
