### ISSUE TITLE
v306 Oblivion - BOSS Not Appearing...

### ISSUE THREAD

**Issue by ghost** [wrye-bash/wrye-bash#350]
Hello,

I have BOSS 2.3.2 installed and I thought at the bottom left of the GUI in Wrye Bash BOSS should have an icon appear I can launch it from?

thanks

**Comment by Geyup** [comment]
Forgot to mention this is on Win7 64bit

I thought this issue was resolved, looking back on the changes of the older versions I see mention of what appears to be BOSS related?

I'd really love to be able to make this work...

thanks

**Comment by Utumno** [comment]
There is an ini setting for pointing to the boss installation:

    sboss=C:\BOSS\BOSS.EXE

Keep using the python version I'd say - and do give a whirl to latest 307 - it's one year of work ahead

**Comment by Geyup** [comment]
Why not just use the standalone? I read for the basics it's what you want, and python for developing...

Hmm

thanks

**Comment by Geyup** [comment]
I found in the Mopy dir bash_default.ini and at the bottom under Misc. Tools that line;

sboss=C:\BOSS\BOSS.EXE

I changed it to;

sboss=C:\BOSS\boss.exe since it's not in uppercase and it does nothing, the default setting, nothing too...

hmm

**Comment by Sharlikran** [comment]
Utumno, the standalone is on average downloaded 10 times more then the Python version.  Also the user is using this with Oblivion and wants BOSS integration.  So there is no reason for him to update to 307 ever since it only has LOOT support.  

Not that it matters since the LOOT taglist is included but most people don't know that I add the Bash Tags from the Oblivion BOSS masterlist to the LOOT Oblivion masterlist so that the auto tag functionality is the same.  I have not updated that in a while though.  I will have to make sure it's current again some time soonish.

**Comment by Utumno** [comment]
>  So there is no reason for him to update to 307 

Really ? So there's nothing added to 307 for oblivion you think ? Like 100s of bugfixes, performance and new features ?

**Comment by Sharlikran** [comment]
@lojack5 I was very specific about the user wanting BOSS support in place of LOOT support.  I was in no way unkind nor disrespectful.  I in no way indicated that newer versions weren't worth using.

**Comment by Geyup** [comment]
Actually I'm using standalone now, don't really care to have all the deps installed...

Thanks all...
