### ISSUE TITLE
Override skips doesn't work

### ISSUE THREAD

**Issue by Owyn** [wrye-bash/wrye-bash#363]
I was trying to install FNIS http://www.nexusmods.com/skyrimspecialedition/mods/3038/? for Skyrim SE, I checked "has extra directories" - so it unskipped most files but some still were skipped, so I checked "override skips" and **nothing** changed at all - same number of skipped files still present

latest Wrye version

**Comment by Utumno** [comment]
Please don't post more issues here - this is not a discussion board. Post in the thread and ask for help and only if it turns out a bug post here.

This is not a bug description - what does it mean " most files " " but some still were skipped " " latest Wrye version " etc ? Have you read https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug ? Where is your bugdump ?

So ask at the thread posting all the needed info and ask for help then - if it turns out a bug I reopen

**Comment by Owyn** [comment]
Are you saying you can't reproduce the problem with the link given?

**Comment by Utumno** [comment]
See the reply by @Sharlikran in http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-2#entry25313410

**Comment by m0lz** [comment]
@Owyn See also the Advanced ReadMe, Skipped files section

http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#bain-skipped
