### ISSUE TITLE
Some packages of mod won't show up or install

### ISSUE THREAD

**Issue by Owyn** [wrye-bash/wrye-bash#364]
NNM installs mod fine but with Wrye heads of NPCs would be missing cause of incorrect installation

this mod:
ESP for it: http://www.nexusmods.com/skyrimspecialedition/mods/11/?
and required files for it: http://www.nexusmods.com/skyrim/mods/71054/?

Standalone Wrye Bash latest version

Bug description - be sure to include:

    what you did (step-by-step), install both mods, uncheck ESP of 2nd one after installation
    what you expected, - that mod would work (check by spawning Hulda npc)
    what happened. - but it didn't (heads of NPCs missing)
    what I did to fix it - use Nexus Mod Manager instead of Wrye one - and it installed fine

details: I think it's cuz Wrye just ignored "characters" folder with lots of files in it, it wasn't possible to install it at all, not sure.

bash.ini, no patches

Tell me if you can't reproduce it, I'll provide the log then. (now I stopped using Wrye cuz it's simply not able to just install mods from the box)

**Comment by m0lz** [comment]
Owyn you have opened an issue with Wrye Bash, when it is not an issue with Wrye Bash. Some mod makers do not make their mods zips Wrye Bash compatible, and the only option then is for the user to ask the mod author kindly to make it Wrye Bash compatible, or in the case that the mod author does not use or even understand Wrye Bash themselves .. the user of the mod rearranges the package to make it Wrye Bash friendly, and yes, this circumstance happens to many people who eventually come to the same conclusion, do it yourself is sometimes best.

This is not a problem with Wrye Bash itself. Nor can the modding community members expect one person programming Wrye Bash to go and solve all of the problems with the thousands of mods out there. If you do not have the knowledge to rearrange the package and all of its requirements, you are probably better off not using Wrye Bash and just use NMM.

There is an easy to follow guide by Alt3rn1ty which explains a bit about making Simple and Complex BAINs for Wrye Bash here http://www.nexusmods.com/oblivion/mods/35230/?

**Comment by Utumno** [comment]
Thanks @m0lz - please have a look at the thread

**Comment by Owyn** [comment]
> it is not an issue with Wrye Bash. 

@Utumno

But how about some compatibility? Why would authors of mods want to make their mods compatible with every single mod manager out there instead of devs of those managers following mainstream standarts of mod-packages (NMM)?

**Comment by m0lz** [comment]
Yes, tell us Owyn, why didn't the makers of NMM follow the Wrye Bash way of doing things ?

Wrye has been around since before any of the series of xxMM's came along
OBMM was preceeded by Wrye Mash and Wrye Bash
FOMM and NMM have just followed on from OBMM
Why should Wrye Bash have to change such a reliable and brilliant method of installation as BAIN is, and upset the millions of users of the same method because one user thinks Wrye Bash should be made compatible with NMM, when in fact the reverse ought to be true ?

Mod Organiser was made to understand Wrye Bash packaging, and even went as far as using the same wizard scripts which Wrye Bash uses. If Tannin could do that making a newbie mod manager compatible with all that has gone before .. then why not NMM aswell ?

Most mods packaging are actually Wrye Bash compatible without any thought from the author needed

And who would change all of the old mods designed for Wrye Bash aswell as other mod managers, for four games ( including all the abandoned ones where permission to change them may not be possible ), to any new method of installation introduced ?

**Comment by Infernio** [comment]
Obsolete as of #380.
