### ISSUE TITLE
wxPython Error

### ISSUE THREAD

**Issue by Esquirua** [wrye-bash/wrye-bash#378]
the issue isn't really with your program persi, but I keep getting this message when I rebuild a Bash Patch
wxPython stdout/stderr Error:
Error in JKs Towns.esp

I was wondering if you could enlighten me as to how I can use this error message to narrow down what is going on?

**Comment by Metallicow** [comment]
It isn't an error from wxPython. wxPython is just the GUI kit being used. That window pops up when a print statement is used or for debugging and also to display bugs. Did you get a traceback?

**Comment by Esquirua** [comment]
not that I saw? how would I know, also thanks for the response

**Comment by Metallicow** [comment]
well, that says there is an error in the esp plugin, so I would guess it is a problem that the author should fix.
Let's see what @Utumno thinks. He is more familiar with the codebase.

**Comment by Utumno** [comment]
Post at the forum threads in `Questions ? Feedback ?` section https://github.com/wrye-bash/wrye-bash#questions--feedback- -- fill in the info detailed in the https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug - especially produce me a bugdump. If turns out a bug in Bash (I doubt it) I will reopen. 

Thanks @Metallicow for chiming in!
