### ISSUE TITLE
Feature Request: Sync Archive From Data

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#391]
Quoting Dwip from 2011:

> - Is there already existing, or is it possible to get a way, to re-add files from my Data folder back into the BAIN archive they came out of? I've got a whole load order I just spent a lot of time cleaning, and it's the sort of thing where I'd just as soon put the cleaned esps back into the archive in case of reinstall, but there doesn't seem to be an easy way to get there from here, but you look at BAIN and say "Yes, but you'd think it could do that." Or maybe you can and I just can't figure it out. Who knows.

Basically what he was asking for back in the day was a feature to allow repackaging an install archive in BAIN based on what's currently in the Data folder. This would require the package to have been initially installed by BAIN of course.

Right now, there's a crude way to work around this:

1. Unpack archive to project
2. Sync project with Data folder.
3. Repack project back into archive.
4. Delete project folder.

Sync Archive From Data would instead be:

1. Right click archive, select Sync From Data
2. Wait while files are gathered and the archive is updated.

This would be quite useful for archives that have files that ended up needing cleaning or whatever so that the archives one keeps in their folder will be up to date the next time they may need to reinstall it.

Obviously not a priority but it was a good enough idea that I wanted to make sure it got preserved for future consideration.

EDIT(utumno): svn link from #41 https://sourceforge.net/p/oblivionworks/enhancements/216/

**Comment by barcharcraz** [comment]
should this sync overwrites and conflict losers or just files that are mismatched and have no match with another mod.

I bet the common usecase is for config files and whatnot.

**Comment by Arthmoor** [comment]
The only thing it should do is update the files in the installation archive to match what's currently in the Data folder for that mod.

**Comment by Utumno** [comment]
Hi @barcharcraz and welcome.
I would rather see you working on this than python3/wx4 which is a huge rewrite - interested in seeing some code ;)

**Comment by warmfrost85** [comment]
This is the same request as #41. As this has more activity, close 41.

**Comment by Arthmoor** [comment]
Didn't even notice that issue or I'd have simply commented on that one instead. Oh well. What's done is done. :P

**Comment by warmfrost85** [comment]
7-zip can unpack 7-zip, zip and rar archives. It can also create 7-zip and zip archives but can't create rar archives. Archives would either be updated in-place (which 7-zip can do for 7z and zip files but not rar files) OR unpacked, synced with Data folder then repacked. However currently there isn't a way to create a rar archive or update one in-place.  

Can only use WinRAR for 40 days without buying it (although they seem to be forgiving on that timeline). I don't think it's open enough to add as a dependency.

Otherwise could BAIN handle it if, in this process, we converted the rar archive to a 7z archive (without needing to uninstall the original rar archive and install the new 7z version)? If we converted a rar archive to a 7z archive would users complain or would there be some other undesirable side effect. 

In-place updating would be the fastest and safest approach but doesn't support rar archives.

Thoughts?

**Comment by Infernio** [comment]
Don't worry about rar files, we can just gray the option out for those.

**Comment by Utumno** [comment]
> Otherwise could BAIN handle it if, in this process, we converted the rar archive to a 7z archive (without needing to uninstall the original rar archive and install the new 7z version)

Yes I'd say - so for rars we could either disable or create a new 7z package (I am not fun of rar exactly because of these complications)

**Comment by warmfrost85** [comment]
For your review, here is a commit for this issue. As stated above, rar files are not supported and the option to sync them is grayed out. This was merged with the nightly branch a few minutes ago.

https://github.com/warmfrost85/wrye-bash/commit/ce92150ebca9ae6ad145c93b39ec9e35e2e69dca

This works with any archive that has only one version of a
missing or mismatched file. Since the in-place update process uses
recursion to find files, files with many versions would all be updated.
This works with BAIN simple structured 7z and zip archives.
Rar archives are not supported. Some fomod, wizard and complex BAIN
archives will work but many won't. The user will get a warning message
when attempting to Sync from Data an archive containing file with more
than one version.

More details in the commit message.

**Comment by Infernio** [comment]
@warmfrost85 Thanks! I stuck it on nightly, with some BAIN refactoring thrown in to allow it to work with archives that have 'duplicate' files (still pretty dreary code in bain.py, didn't want to shove refactoring that onto you :)).

**Comment by Infernio** [comment]
Whoops, my change doesn't actually work correctly. Will take a look and fix it in a bit.

**Comment by Infernio** [comment]
I ended up rewriting the implementation completely in f574ee578d5bb583efe187c6bc30d71620e427ec to avoid the 7z add/update command entirely. See that commit for some pros/cons.

**Comment by warmfrost85** [comment]
Thanks Infernio. More functionality with less code! I'll look over your changes. Your changes demonstrate the benefits of a deep understanding of the code base. You've made big improvements to WB in general. Thanks for all you work. Of course, big big thanks to you too Utumno!!

**Comment by Utumno** [comment]
Welcome @warmfrost85 ! Unfortunately despite our efforts, there is much to be done, especially in view of py3 transition and all the worms that this uncanned. Infernio started writing some tests (cause we are really bored you see :P) - since you have experience with BAIN already, maybe trying to add some tests for common BAIN operations? (it's a hard nut probably cause you have to mock structures, but may prove not too hard)

**Comment by warmfrost85** [comment]
@Utumno I don't see anything about tests in the wiki. Although tests are always helpful, I assume in this case you need tests to verify py3 code doesn't break functionality. Where are the current tests? _Examples of how you do it are always nice._

**Comment by Utumno** [comment]
Yep oops - I meant this branch 1381e0feae718dff1cc5138b860e20bec1d17ff0

**Comment by Infernio** [comment]
aac47efb1460dd892f8f56d3ea67b588181460e3 shows some example tests, but basically:
1. Place binary files needed for testing in the https://github.com/wrye-bash/test_resources repo
2. Write integration tests - e.g. one test I have for cosaves iterates over all cosaves (see the `iter_cosaves` and `_map_cosaves` functions in there), reads them in and writes them out to a temp path, then compares the checksum to verify that we write out identical cosaves. You can also use meta files to store 'expected' information along with the file, see test_get_master_list for a good example.
3. Update the test_resources submodule
4. The CI will then clone that submodule and use the resource files when running your tests

You'll have to base yourself off of inf-474-initial-ci, since it's not merged yet (but probably could be).
Also, be careful not to go too low-level with tests. I originally had a bunch of tests for cosaves that would use a gigantic meta file and verify every single detail read correctly. I ditched that after reasoning it would just break on the first refactoring that touches the tested code (turned out to be correct: 222d6b13bdbfaea0c7414317f0a984a215a2d2f4).
