### ISSUE TITLE
Load order esls revisit

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#429]
Sources:

- https://tes5edit.github.io/whatsnew.html -> Load order handling
- https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp/&do=findComment&comment=174631
- https://tes5edit.github.io/docs/9-appendix.html#s_9-2
- https://www.creationkit.com/fallout4/index.php?title=Data_File
-  https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp/&tab=comments#comment-169297
- https://github.com/loot/loot.github.io/blob/master/docs/help/Introduction-To-Load-Orders.html

Points to verify:

> I don't recall if anyone tested the .esm handling with anything other than SSE and FO4. It would probably be safe to assume that the older games handle the .esm extension the same way SSE and FO4 do though.

TODOS:

- [x] Wrye Bash should not allow enabling 254 non-ESL mods because occupying the FE slot will cause corruption during gameplay. That slot is now reserved for the use of ESL flagged files in SSE and FO4.
- [x] ~~Creation Club files. The order of these is specified by the *.ccc file for each game. If that file is missing then it falls back on a hardcoded list. -> __add this hardcoding to bash__~~ -> moved to #309
- [x] ~~revisit master/children warnings - add a big fat one for esm or esl flagged files that have an esp as master~~ -> moved to #309

@Arthmoor - did I get those right?

**Comment by Utumno** [comment]
Can someone (@Arthmoor ?) test if esms without the esm flag load before esps in the older games (OBlivion fallout3/nv, Oldrim)

**Comment by Arthmoor** [comment]
Tested on Oblivion. File name with .esm extension but no ESM flag is still loaded in the same area as the other ESM files. So it would appear this behavior is consistent, and IMO safe to assume it exists for all the other games too since their basic file handling has not changed.

**Comment by Utumno** [comment]
Thanks @Arthmoor - this simplifies things a lot

**Comment by Sharlikran** [comment]
```
Added missing comma to dataDirsPlus
[FO3] Updated MreLeveledList
[FNV] Updated MelModel
[FO4] Updated class MelModel
Update RecordHeader.topTypes
  - Also updated RecordHeader.recordTypes.
  - Removed duplicate AMMO entry which caused Bash to make two groups of the same type and merge the same record with the same FormID into the Bash Patch.
Update Fallout 4 records.py
  - Imports the same as Skyrim SE to facilitate better importing
  - Updated Leveled List definitions as they are different from Skyrim
Tweak to NamesPatcher to remove FACT
  - Nothing else patches it and just breaks it.
Remove unused Alias Patcher
Add loadInfos for MreDial
Remove Add master from all versions
  - This does not update FormIDs and could not do so because some records are not fully decoded.
Remove MelOptStructA
Update MreLens
Updated MreLeveledListBase with extra flag for Skyrim SE
  - Won't effect other games that don't use it because the flg won't be set
Fix Exterior Cell Grup Indices Order
[FO4] Disable ESLify flagging and ESL verification support
  - All records have to be decoded for this to work
Update messages to display ESL rather then Mergable
Disable Merge Plugins [Skyrim SE/Fallout 4]
  - This is in place of having improved ESL
Added Ghetto ESL qualification check
Added Mod_FlipEsl
checking commits for ESL in Bash Patch
  - Commit 1: c906ebb
  - Commit 2: 59f088e
ESL flagged files do not count toward max_espms
Adding Default values to MelOptStruct
  - Apparently MelOptStruct looks at default values rather then the data istelf. This should probably be updated because testing WRLD records, WCTR and NAM4 were not carried over into the Bash Patch. An additional Bash Tag is probably not needed.
Updated class MelModel
  - This discards textureHashes since they are not used in loose files. Which fixes an issue with adding Form Version 44 to the header of Skyrim SE plugins that contain textureHashes.
Remove Critical Oversight
  - So there was a discussion in wrye-bash#342 and wrye-bash#403. I asked the current maintainer to suppress the error for the official game files.
  - https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=170862
  - Commit wrye-bash@589ece6 was submitted instead which is incorrect.
  - It is incorrect because as I stated many times in 2017 all records for Skyrim SE are written in Form Version 44 format. Only people who do not listen to me or people who do not understand programming continue to needlessly speculate what is and is not happening.
C.GridFlags C.MaxHeight
Taglist Update LOOT v0.13
Update Advanced Readme
Add New Cell Tag C.Locklist
Add C.Regions to Oblivion
Syntax Correction for not in checks
Add Persistent Cells to Patcher Check
Hacky hack hack
Fix C.Regions ITM & ITPO
Refactor Cell Importer
Fix Duplicate Records In Stats Parsing
Enabled additional patchers for Skyrim
Account for truncated records in Skyrim.esm
```
ESL Support (following LOOT and xEdit support) has been tested since October (over 400 downloads) as well as what is listed above. Some of the fixes that CptMcSplody implemented are more critical. I have not hear from Wrye at this time, but he may be trying to enjoy the holidays. I will probably try to enjoy the holidays for now too.

**Comment by Utumno** [comment]
@Sharlikran @Arthmoor I am ready to merge the esl support to stable branch (dev) 

https://github.com/wrye-bash/wrye-bash/compare/dev...14c5d4137fd33bae73c1037759eb413b577a33ce

however I have some questions:

- do we allow esl flip for fallout4? @Sharlikran version drops the esl scan for FO4 but still keeps the button - although mergeable are not esl capable anymore
- I do convert esms to esls - anyone write me some docs for that button? This is the warning, should be updated and docs for the menu added

		message = (_(u'WARNING! For advanced modders only!') + u'\n\n' +
		+            _(u'This command flips an internal bit in the mod, converting an '
		+              u'esp to an esl and vice versa.  Note that it is this bit OR '
		+              u'the ".esl" file extension that turns a mod into a light '
		+              u'master.  We therefore disallow selecting an esl for '
		+              u'converting into a light master (as it always is), as well as '
		+              u'an esm as it is reported to be reserved for official mods.'))

- The hasHighForms method does not really check for high forms also checks for a bunch of other things - among which if plugin has the master flag it disalows being converted in esl - but as @Arthmoor said there is no reason for this right?

- mods_metadata checks escape me - the message says:

		+                    log(_(u'Following mods have an ESL flag, but do not '
		+                          u'qualify.These mods have one or more ObjectIDs '
		+                          u'that are greater then 0xFFF.'))

but the test calls another function:

		+            if bush.game.check_esl:
		+                for m in modInfos.esl_flagged:
		+                    if not check_esl_topsSkipped(modInfos[m]):
		+                        if modInfos[m].header.flags1.eslFile and m not in modInfos.mergeable:
		+                            if not modInfos[m].abs_path.cext in (u'.esm', u'.esl'):
		+                                if not (modInfos[m].header.flags1.esm and modInfos[m].header.flags1.eslFile):
		+                                        removeEslFlag.add(m)

`check_esl_topsSkipped` - shouldn't it call the `hasHighForms`?

- What does check_esl_topsSkipped does ? I need a docstring for that one

See also checklist in https://github.com/wrye-bash/wrye-bash/issues/260#issuecomment-451702644

**Comment by Arthmoor** [comment]
> I do convert esms to esls

What do you mean by this?

As you mentioned below that, there's no technical reason why you can't flag an existing .esm file with the ESL flag. So long as all of the proper form limit checks are being done (that whole 0xFFF thing).

It's also worth noting that there isn't any restriction on what types of records a file can have to qualify as an ESL. As long as it has no forms beyond the limit, any file should qualify.

**Comment by CptMcSplody** [comment]
@Utumno If I recall correctly, ESM were left out because something else needed to be fixed in the records first, I'll see if I can find the reason.

**Comment by Utumno** [comment]
Thanks @Arthmoor @CptMcSplody 

I mean I allow esms to be flagged as esls, although Sharlikran didn't
So I drop esl flagging from Fallout 4?

@Sharlikran is doing some records checks for esl qualification - not sure about those too. Sharlikran I hope you get notified - if not can someone reach him? I need your comments on those too

**Comment by Arthmoor** [comment]
I don't know why there's any record checking going on at all because it doesn't matter what records are in those files. As long as none of the forms inside the file exceed 0xFFF it's safe to add the flag.

I also see no reason to bar this from working in FO4 either because FO4 has the exact same rules for what can qualify that SSE does.

**Comment by Utumno** [comment]
We'll have to ask @Sharlikran too

**Comment by Sharlikran** [comment]
As I have said several times I could not find a way to check the new records in Wrye Bash code reliably. When I tested my initial changes allowed flagging a file that did not qualify. Because of that I imposed restrictions. The report stated to check in xEdit because I didn't want people flagging files that don't qualify.

If changes have been made and testing has been done and Wrye Bash can PROPERLY detect the qualifications of a file then disable merging for Fallout 4 and Skyrim SE and make sure the merge patches menu option is replaced for games that support ESL flags.

Then instead of asking the ESL flag questions several different ways and thinking there has to be some profound reason, look at the docs I made for xEdit that I have linked before. That has all the answers and is easy to understand. 

Then don't allow a file to have both the ESM and ESL flag because that is reserved for CC files. I keep repeating this and people keep saying other things. It just causes confusion stop it.

Remember Bethesda does not tell us anything no matter how many times we ask. We mimic the Creation Kit. So if the Creation Kit does not do it then we don't. If the game does not do something then we don't.  In those cases, the answer to the question is "just because" and needs to stop being debated. If you want to continue to debate it ask Bethesda yourself for 6 years, get nowhere until you realize you never will, and then maybe you will understand why "just because" is sometimes the only answer you are going to get.

**Comment by Arthmoor** [comment]
> Then don't allow a file to have both the ESM and ESL flag because that is reserved for CC files. I keep repeating this and people keep saying other things.

That's because there is no technical reason for why this cannot be done. A file with both the ESM and ESL flag is perfectly valid and the game will treat it as you would expect for any ESM flagged file while putting its forms into the FExxxxxx space. I in fact have 2 files that do exactly this in my game and they work just fine.

**Comment by Sharlikran** [comment]
But saying that there is no technical reason for it still doesn't mean that we have a reason that it should be allowed.

If a file needs to be an ESM then it should have the .esp or .esm extension.

If a .esp qualifies to have an ESL flag then give it the flag.

If any file is going to be made into an .esl file, then add the .esl extension and the ESL flag. The game will assign the esm flag even though it doesn't have the flag on disc just as eElminster has print it out.

Follow one standard and then there isn't any confusion. The standard being do what Elminster has pointed out. 

If elminster's reason isn't good enough for you then mimic the creation kit or the game and don't do something just because it happens to work if the official tools don't do it that way.

**Comment by Arthmoor** [comment]
There's one very good reason: The filename is already a .esm file and you don't want to screw over someone's load order by changing the extension to .esl. There is no good reason whatsoever to do this when all you need to do is apply the ESL flag to the .esm file and be done with it.

If we're going to mimic the CK then I suggest you need to rethink your logic because a .esp file with the ESM flag is not something you can make with the CK either. Nor can you make an actual .esm file with it.

This does not apply to the way SSE and FO4 are handling their official DLC files because it's crystal clear that those files are hardcoded to load in a certain order and nothing Bash or any other mod manager can do will change that, so by disallowing one to touch that, it ends the confusion that existed at one time. There is no such confusion to end with setting the ESL flag on a .esm file.

**Comment by Sharlikran** [comment]
Well no but I hope nobody will ever change a .esm file to a .esl file. I never suggested that though.

As for the other there is no reason trying to use what I said as a double edged sword. People have false flagged files for a very long time. Don't split hairs over it.

**Comment by Utumno** [comment]
Glad this esm thing is cleared up - 3 more questions to go

@Sharlikran my code on flagging was based on your code - I need you to review this. I need you also to answer the questions I asked on your code:

- mods metadata - the message says it checks for forms > 0xFFF but the code does not do that - what am I supposed to do here - see: https://github.com/wrye-bash/wrye-bash/issues/429#issuecomment-455804230
- in your check you load only the mergeable records - why?
- so what does check_esl_topsSkipped does? I need a docstring for that one

**Comment by Sharlikran** [comment]
1. I looked at mods mods_metadata.py and I didn't see the code that checks for forms > 0xFFF, did you mean _mergeability.py?
2. Because if you don't then the check fails since there is no record.fid to look at in _mergeability.py
3. I don't know how to explain it.

```
    for type,block in modFile.tops.iteritems():
        for record in block.getActiveRecords():
            if record.fid >> 24 >= lenMasters:
                if (record.fid & 0xFFFFFF) > 0xFFF:
                    eslCapable = False
                    if not eslCapable:
                        break
        if not eslCapable:
            break
```
How would you word that if `record.fid` was looking at xxYYYYYY, which the mas just returns YYYYYY. Then when YYYYYY = 000A2F it won't be `> 0xFFF` but when YYYYYY = 0F1350 if will be greater then 0xFFF?

**Comment by Utumno** [comment]
Ok thanks @Sharlikran for replying to my questions that is really helpful

1. No it's in mods metadata - your version says:

```
+                    log(_(u'Following mods have an ESL flag, but do not '
  +                          u'qualify.These mods have one or more ObjectIDs '
  +                          u'that are greater then 0xFFF.'))
```

but what has called is:
```
+            if bush.game.check_esl:
	+                for m in modInfos.esl_flagged:
	+                    if not check_esl_topsSkipped(modInfos[m]):
	+                        if modInfos[m].header.flags1.eslFile and m not in modInfos.mergeable:
	+                            if not modInfos[m].abs_path.cext in (u'.esm', u'.esl'):
	+                                if not (modInfos[m].header.flags1.esm and modInfos[m].header.flags1.eslFile):
	+                                        removeEslFlag.add(m)
```
so it calls `check_esl_topsSkipped` but this does not check for `greater then 0xFFF`. Anyway shouldn't we call `hasHighForms`

1a. `hasHighForms` returns true when mod does _not_ have hiogh forms (and some other checks) so probably should be called `hasNotHighForms` or better `is_esl_capable`, right?

2. hmm, so this means that if we have not decoded the record we can't tell if there are record.fids > 0xFFF. So instead of disabling for FO4 we should just say for those mods (that have undecoded records) that user should check xEdit. Not really familiar with records code so I could use some help here

3. Hmm so this is the part that checks if it has formids bigger than 0xFFF. I got this much but what is the purpose of this:


```

+    #--Load test
+    mergeTypes = set(recClass.classType for recClass in bush.game.mergeClasses)
+    modFile = ModFile(modInfo, LoadFactory(False, *mergeTypes))
+    try:
+        modFile.load(True,loadStrings=False)
+    except ModError as error:
+        if not verbose: return False
+        reasons += u'\n.    %s.' % error
+    #--Skipped over types?
+    if modFile.topsSkipped:
+        if not verbose: return False
+        reasons += u'\n.    '+_(u'Record type: ')+u', '.join(sorted(modFile.topsSkipped))+u' ' \
+                                u'; currently unsupported by ESLify ' \
+                                u'verification. Use xEdit to check ESL ' \
+                                u'qualifications and modify ESL flag.'
````

My understanding is it checks if the mergeable records from the mod can be loaded and if mod has some records that are not in bush.game.mergeClasses we can't decide. Am I correct? But if yes should we not load _all_ records and then say we can't decide if some of the records are not fully decoded?

**Comment by Arthmoor** [comment]
@Sharlikran 

> Then don't allow a file to have both the ESM and ESL flag because that is reserved for CC files.

This is what I was getting at when I said there's no reason not to allow this. A .esm that has both ESM and ESL flags is entirely valid and is not reserved for CC content at all. I only brought up the .esl file in my response as an example of why ESL flagging an existing .esm is not only valid, but preferred, because it won't affect their saves.

**Comment by Sharlikran** [comment]
The confusion is the reused variables. It's on purpose to prevent merging files when the game has ESL support. Also it's to prevent duplicate code. I have not had time to examine your code. Since you are not using mine then I have no idea what the routines do now. I'm barley 40% through the changes. If I have time I'll keep working on it.

**Comment by Utumno** [comment]
Thanks @Sharlikran - the end result will be simple you will be able to review easily

**Comment by Infernio** [comment]
Currently going through and leaving you feedback on some of the esl commits on utumno-wip.

**Comment by Utumno** [comment]
Posted some new and was working last couple hours on a refactoring I talked about - will push that too but it's kinda half baked

**Comment by Infernio** [comment]
I made a small change to mark ESLs that also have a master flag with a different color - [you can see the result here](https://user-images.githubusercontent.com/2845240/51790200-3f276900-2192-11e9-8bf6-a0222bd26142.png). Will push that in a minute on a new branch.

The color is somewhat similar to the one used for `NoMerge` plugins right now. That shouldn't really be a problem, since `NoMerge` tags aren't supported on games with ESLs, but I went ahead and changed the color for `NoMerge` in a separate commit to avoid the problem altogether.

**Comment by Utumno** [comment]
Actually was on my mind too :P

**Comment by Infernio** [comment]
The readmes will also have to receive some significant rewrites for this - they were last updated for ESL support back in the initial merge: https://github.com/wrye-bash/wrye-bash/commit/d507111773d459e41468ac835955fe88915e622e

Will obviously have to wait for Feles' changes though :P

**Comment by Utumno** [comment]
Or review those changes and merge (as in a single commit cherry pick) - If you want @Infernio be my guest :)
