### ISSUE TITLE
No-op lines in multitweak_assorted.py

### ISSUE THREAD

**Issue by syntaxaire** [wrye-bash/wrye-bash#471]
While working on #470 I noticed a couple of lines in `multitweak_assorted.py` that look like they're supposed to be doing something, but aren't.
```python
rec_text.lower()
```
occurs twice in the file. I don't know enough about what this code is doing to know whether this is already causing subtly corrupt output, or whether *fixing* it would *start* causing corrupt output.

**Comment by Infernio** [comment]
For something this minor, just ping from an existing issue or commit :)

Here's how I would go about figuring out what that code does:
Looking at the calls in question, a quick `git blame` shows that they've been unchanged (barring some variable renaming) since at least 2014.

Taking a look at the logic in the `AssortedTweak_DarnBooks.buildPatch`:
```python
for record in patchFile.BOOK.records:
    if record.text and not record.enchantment:
        rec_text = record.text
        # ... whole bunch of code altering rec_text
        if rec_text != record.text:
            record.text = rec_text
            keep(record.fid)
```
So if our code in that loop makes the string `rec_text` distinct from the string `record.text`, we will include a version of the record with changed text in the Bashed Patch (that's what the `keep(record.fid)` line does).

What is `record.text`? It's in `game/oblivion/records.py`, class `MreBook`:
```python
MelString('DESC','text'),
```
This part is something you have to get used to at first - if the variable in question comes from `ModFile.****.records`, and `patchFile` is an instance of `ModFile`, then you'll have to look for a matching definition in `game/GAME_NAME/records.py`.
In this case, that's easy - we're iterating over BOOK records:
```python
for record in patchFile.BOOK.records:
```
...so we want to look at `MreBook`. Since this patcher is Oblivion-only, we want the `game/oblivion/records.py` version of `MreBook`.

Taking a look at some typical BOOK/DESC entries in TES4Edit, they look like this:

![BOOK_DESC](https://user-images.githubusercontent.com/2845240/66522839-a1d94e80-eaee-11e9-8ec3-e84c3ac0f583.png)

So just regular, human-readable text with some markup formatting. What would happen if we did `rec_text = rec_text.lower()`? This, obviously:

![BOOK_DESC_lower](https://user-images.githubusercontent.com/2845240/66523204-976b8480-eaef-11e9-88e8-9a0685f04a6a.png)

So, all the text is lowercase now. With that, it would definitely be distinct from `record.text`, which means we will write it out. For every record in `patchFile.BOOK`, which just so happens to be every BOOK record in the entire load order:
```python
# This is called once for every mod in the load order that has BOOK records
def scanModFile(self,modFile,progress,patchFile):
    # maxWeight = self.choiceValues[self.chosen][0] # TODO: is this
    # supposed to be used ?
    mapper = modFile.getLongMapper()
    patchBlock = patchFile.BOOK
    id_records = patchBlock.id_records
    for record in modFile.BOOK.getActiveRecords():
        if mapper(record.fid) in id_records: continue
        if not record.enchantment:
            record = record.getTypeCopy(mapper)
            patchBlock.setRecord(record)
```

So, we most likely do not want to uncomment those calls - in fact, we probably want to remove them, since they sit in somewhat tight loops and CPython does no optimization to avoid such useless calls.
