### ISSUE TITLE
Rethinking Ratings and Groups

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#484]
There is a feature on the mods tab UI labeled "Ratings". The purpose of this code is unknown and likely not in use by anything and doesn't really serve a useful purpose in general

Infernio also says the code is ugly :P

Right click on any file on the mods tab and a menu for it will show up with several numerical options as well as a sub menu for editing ratings.

**Comment by Infernio** [comment]
Unfortunately, dropping the ugly code (`_Mod_Labels` - does some weird things with `self`, has a bunch of warnings and `##:` comments, etc.) isn't possible unless we also drop groups - not sure how much outcry there would be from users regarding either of these being removed. Anyway, something to discuss, so marking this as discussion and 308.

**Comment by Verayth** [comment]
The ratings column is useful for much more than just rating the mods as you can see from my expanded menu below.  
![WryeBash-Ratings](https://user-images.githubusercontent.com/8931332/72772412-c656c380-3bd1-11ea-9198-04b314175e93.png)

**Comment by Utumno** [comment]
Then it stays - but what should be the difference from groups (I vaguely remember fixing all this on another plane of existence)

**Comment by Infernio** [comment]
The backend implementation is the exact same (`_Mod_Labels`), but groups have a bunch of extra baggage because you can import/export them to CSV files.
Other than that, they only differ in their defaults - ratings have some numbers as the default, while groups have a bunch of categories like 'Clothing', 'Magic', 'NPC', etc.

Also, IIRC there was some hellish arcane feature (bola? balo?) a long time ago that relied on groups to reorder plugins, but that's been dropped in 306, or maybe even earlier than that. Or maybe I'm mixing that up, will go take a look.
