### ISSUE TITLE
Scripts Tab

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#502]
Let's formalize this - 'way too early POC' branch is at [inf-scripts-tab-poc](https://github.com/wrye-bash/wrye-bash/tree/inf-scripts-tab-poc), but this is a dead end.

The idea is of course to offer a one-stop-shop for all your script management needs, in the swiss army knife spirit.

Ideally we'd show single entries for PEX files and PSC files (with the icon on the left side indicating if the source is present), similar to the wizard icon.
Really advanced features would be to offer (de)compilation, allow grouping scripts into (virtual) folders so you could do full mod development inside WB, etc.

Note that this is *really hard and far off* and will require:
- [ ] Reading/Writing PEX files (semi-done in the branch above, but the API is terrible)
- [ ] Reading/Writing PSC files
- [ ] Compiling/Decompiling between the two
- [ ] Refactoring the model side of the tab infrastructure to permit multiple sources (`scripts` and `scripts/sources`, see also #246) and virtual sources (scripts from BSAs, in this case).
- [ ] Refactoring the GUI side of the tab infrastructure (see also #63 and #190)

Some resources and inspirations:
- https://github.com/Orvid/Champollion
- https://en.uesp.net/wiki/Tes5Mod:Compiled_Script_File_Format
- https://github.com/fireundubh/pyro

**Comment by leandor** [comment]
Sorry for the noise here, but I wanted to comment something that I've noted recently while going over my local install _(while looking at conflicts and resolving them and other things to sort out,)_ and I still don't know from where they come/when does it start.

I've going over my Papyrus.log for warning and errors and there seem to be a lot of warning generated due to differences in the PEX files installed and what the specific mods you've installed want from them.

At this point I'm not sure if it's an inherent problem in some mods (they come already in that state) or it's something that it's created due to other mods somehow changing the VMAD records in ways that create such warnings, or perhaps even some mods overwriting PEX files inadvertedly (perhaps from inside a BSA?)

So, I wanted to add here that a way to detect such inconsistencies could be interesting to have as part of this Tab!

Also, another thing it'd be cool to have is a way to show/highlight mods that refer to script files (PEX) that for some reason aren't installed (perhaps incorrect packaging, or non-mentioned dependency, for example.)

Also, I assume some of the warnings/errors I see come from some PEX files that haven't been re-compiled, maybe? Or perhaps the ESPs haven't been saved with the CK after some PEX files changed?

((PS: Note to add that the warnings I mention don't come from changing mods mid-playthrough. I started my current game from scratch when my mod list was already in-place and I haven't installed/uninstalled mods since then. _Except a few mod updates_))

Examples of errors/warnings I refer to:
```
[04/23/2020 - 01:24:05AM] Cannot open store for class "aaaRedspireIngredientStorageScript", missing file?

[04/23/2020 - 01:24:05AM] Error: Unable to bind script aaaRedspireIngredientStorageScript to  (390A5BBF) because their base types do not match

[04/23/2020 - 01:24:17AM] warning: Property Nocturnal on script FFNAliasDovahkiinScript attached to alias AliasDovahkiin on quest FFNFreedomForNightingales (2723F434) cannot be initialized because the script no longer contains that property

[04/23/2020 - 01:24:17AM] warning: Property FNISPCEA2item on script FNIS_PCEA2PlayerLoad attached to alias FNIS_PCEA2_player on quest FNIS_PCEA2 (55000D62) cannot be initialized because the script no longer contains that property
```

**Comment by Infernio** [comment]
On the backburner - probably the least important of all our `A-new-tab` issues.
