### ISSUE TITLE
ControlMap Handling/Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#503]
From @leandor's post in #400:

>  Add ControlMap_Custom.txt and/or Data\interface\Controls\PC\controlmap.txt patching/tracking/editing support.
> Not sure on how both files relate at all, I assume one is generated from the other.
> Data\interface\Controls\PC\controlmap.txt is a text file and I know for a fact that you can edit it and have stuff added/changed to suit your needs, while ControlMap_Custom.txt (which is located in the EXE folder) is a binary file that I assume the game generates updates automatically, or else the presence of a controlmap.txt overrides the binary file.
> AFAIK, this applies to Skyrim, Skyrim SE, Fallout 4, and probably VR?.
> Some mods require changes made to that file and otherwise different mods are incompatibles with one another even if their change could be potentially entirely mergeable.
> Examples: AH Hotkeys requires patching a couple of entries in order for the auto-cast of spells to work.

Tons of open questions:
- How do these files work?
- What should we let users do with this?
- How do we present this? New tab?
- Is this even worth supporting? I don't want to introduce a second People Tab 😛

**Comment by leandor** [comment]
Gonna try to describe the file format the best I can... all of this is taken from the actual file comments.

From my naive point of view, I see them as a kind of use-case similar to INI files, currently. Where you have a single monolithic file and some special fragments (i.e. the INI tweaks files) can be applied or removed, to/from them.

Basically, here's the rough view of how it works:

- It's a text file. 
- Contains lines organized as rows and each row has columns with values in them. 
- It has separated sections for different "views" or "modes" in the game.. these sections aren't actually defined in the file, they are just marked by comments.
- The number of columns is fixed in each section.
- Inside each section, it presents a linear view of ``Actions`` supported by the game (the value contained in the first column) one per each line, where the subsequent columns are the values and modifiers to be applied to such action.

Here is the description of the content of the file directly from its header:
```
// 1st field: User event name.  DO NOT ALTER!  This field is used to ID events in the code							
// 2nd: Keyboard key ID that will proc this event.  A value of 0xff means the event is unmapped for this device.							
// 3rd: Mouse button ID that will proc this event.							
// 4th: Gamepad button ID that will proc this event.							
// 5th: If set to 1, this event can be remapped to a keyboard key
// 6th: If set to 1, this event can be remapped to a mouse button
// 7th: If set to 1, this event can be remapped to a gamepad button
// 8th (Optional): User event binary flag.  Used to group together related user events, like "Movement" or
// "Menu", so they can be toggled on and off together
//							
// Blank lines signify the start of a new input context.							
// See ControlMap.h for more details on input contexts.							
//
```

And here's a sample of the first section of the file I have in my machine:
```
// Main Gameplay
Forward				0x11				0xff	0xff				1	1	0	0x801
Back				0x1f				0xff	0xff				1	1	0	0x801
Strafe Left			0x1e				0xff	0xff				1	1	0	0x801
Strafe Right		0x20				0xff	0xff				1	1	0	0x801
Move				0xff				0xff	0xff				0	0	0	0x801
Look				0xff				0xa		0xff				0	0	0	0x2
Left Attack/Block	0x70				0x1		0xff				0	1	0	0x841
Right Attack/Block	0x79				0x0		0xff				0	1	0	0x841
Activate			0x12				0xff	0xff				1	1	0	0x804
Ready Weapon		0x13				0xff	0xff				1	1	0	0x840
Tween Menu			0x0f				0xff	0xff				1	1	0	0x908
Toggle POV			0x21				0x5		0xff				1	1	0	0x820
Zoom Out			0xff				0x9		0xff				0	0	0	0x220
Zoom In				0xff				0x8		0xff				0	0	0	0x220
Jump				0x39				0xff	0xff				1	1	0	0xC01
Sprint				0x38				0xff	0xff				1	1	0	0x801
Shout				0x2c				0xff	0xff				1	1	0	0x840
Sneak				0x1d				0xff	0xff				1	1	0	0x881
Run					0x2a				0xff	0xff				1	1	0	0x801
Toggle Always Run	0x3a				0x4		0xff				1	1	0	0x801
Auto-Move			0x2e				0xff	0xff				1	1	0	0x801
Favorites			0x10				0xff	0xff				1	1	0	0x908
Hotkey1				0x02				0xff	0xff				0	0	0	0x908
Hotkey2				0x03				0xff	0xff				0	0	0	0x908
Hotkey3				0x04				0xff	0xff				0	0	0	0x908
Hotkey4				0x05				0xff	0xff				0	0	0	0x908
Hotkey5				0x06				0xff	0xff				0	0	0	0x908
Hotkey6				0x07				0xff	0xff				0	0	0	0x908
Hotkey7				0x08				0xff	0xff				0	0	0	0x908
Hotkey8				0x09				0xff	0xff				0	0	0	0x908
Quicksave			0x3f				0xff	0xff				1	0	0	
Quickload			0x43				0xff	0xff				1	0	0	
Wait				0x14				0xff	0xff				1	1	0	0x808
Journal				0x24				0xff	0xff				1	1	0	0x808
Pause				0x1					0xff	0xff				1	1	0	0x8
Screenshot			0xb7				0xff	0xff				0	0	0
Multi-Screenshot	0x1d+0xb7,0x9d+0xb7	0xff	0xff				0	0	0
Console				0x29,0x94			0xff	0xff				0	0	0	0x10
CameraPath			0x58				0xff	0xff				0	0	0
Quick Inventory		0x17				0xff	0xff				1	1	0	0x908
Quick Magic			0x19				0xff	0xff				1	1	0	0x908
Quick Stats			0x35				0xff	0xff				1	1	0	0x908
Quick Map			0x32				0xff	0xff				1	1	0	0x908
```

As for what kind of tweaks could be applied to this file?

Well, for the mod I had to install I had to tweak two lines, these:
```
Left Attack/Block	0x70				0x1		0xff				0	1	0	0x841
Right Attack/Block	0x79				0x0		0xff				0	1	0	0x841
```
Where I had to add there the key assignments so the attacks are able to be triggered by keyboard... in the normal unmodded file, those entries have a 0xFF in place of the key scan codes:

```
Left Attack/Block			0xff	0x1	0xff		1	1	0		0x841
Right Attack/Block			0xff	0x0	0xff		1	1	0		0x841
```

The codes used there are standard virtual key codes (I think... not sure on the correct specifics on that, but they match the list [here](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes))


As for possible actions to be performed in this file:
- Change the key bound to a specific Event Name (or Action) in one of the three possible entries for that, i.e. keyboard is the second column, mouse is the third column and controller is the fourth column.
- Remove a binding from an Action.
 For example, the case of the Hotkeys normally have two bindings, the number key, and the keypad number key... a common tweak is to remove the keypad keys from there so they are available for other hotkeys.
- Add extra bindings to a given Action: as shown in the entries for Multi-Screenshot and Console, you can have several keybinds associated with one Action separated by commas: ``0x29,0x94``
- Support adding modifiers to Actions: i.e you can require two keys pressed at the same time using ``+`` as separator, that's useful for some cases (i.e. again, liberating more plain keys for use as hotkeys in mods.)

These are all the things I can think of atm. I'm not entirely sure if this could prove useful for a lot of people?
Not sure how common is to have to tweak this file at all.

The thing that could prove useful is to allow mods to come prepackaged with "Control Tweaks" and then Bash would/could auto apply them like it does with the INI tweaks.

**Comment by Infernio** [comment]
On the backburner - INI handling (especially tweaks in BAIN) should be rock solid before we even consider handling tweaks to other config file formats.
