### ISSUE TITLE
How to disable "load order sanitization"? 

### ISSUE THREAD

**Issue by Wolfstorm321** [wrye-bash/wrye-bash#522]
I keep getting this message "load order sanitized, too many mods", with a list of mods removed. However, since the mod list is locked, it wont delete those mods. When I open the game, all mods are disabled, and I cant load a save without crashing. 
How to disable the "sanitization" of the load order? I looked in the docs, but could not find any information about it.

**Comment by Infernio** [comment]
There is no option to disable it, because when Wrye Bash sanitizes a load order, that load order is already broken. 'Too many mods' means exactly that, you are exceeding the maximum number of mods that can be active at one time.

This is also not an appropriate topic for a github issue - see the [Questions/Feedback section](https://github.com/wrye-bash/wrye-bash#questions--feedback-) of the readme. Discord or the AFKMods thread would have been a better place, plus other users can more easily weigh in in those places.
