### ISSUE TITLE
Warn about hash collisions from BA2 filenames

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#558]
BA2s will override each other when the hashes of their file names collide. This will cause the later-loaded BA2 to completely overwrite the previous BA2.
The only way to resolve this is to rename one or both of the colliding BA2s. This should be done by mod authors so that all users can benefit, obviously.

Bethesda uses a CRC-like hashing algorithm for this, as documented here: https://github.com/Ryan-rsm-McKenzie/bsa/blob/ea21a026843b6b834ae70d05076ec7f34faf1cf4/include/bsa/fo4.hpp#L502-L544
Normally, it compares the directory and file hashes as well as the extension. Since all BA2s are in the same folder (Data) and have the same extension (.ba2), we really only need to check the file hash.

Note also that the hashing algorithm only handles ASCII characters - other characters will go out of bounds. So it's probably not a good idea to use non-ASCII characters in your BA2 names :)

**Comment by leandor** [comment]
I've noticed that now when updating mods that come with BA2 (I mean, updating to a new version of the same previously installed mod, to be specific) Bash now complains about Hash collisions after installing the update[1] while the previous mod is still installed. 

The collisions are reported as between the exact same named BA2s (the one previously there and the new one being installed.)

Is this something that's working as intended (i.e. the warning on update, I mean) and then it's something that I'm not understanding correctly about the situation, or maybe that case of a warning should be somehow filtered? (when updating mods, I mean...)

Not sure if that's related to this issue or not? If it's not, feel free to ignore me, and sorry for the noise :)

I'm mostly talking about Fallout 4 here, since it's what I've been playing lately and thus, adding mods and updating them constantly :)

[1] I normally update mods by first installing the new version and overwriting everything, and then uninstalling the old version...

**Comment by Infernio** [comment]
Can you upload a screenshot of the warning? It sounds like you're talking about a new version of a BSA reporting a conflict with an older version right before it's replaced, which is definitely wrong.

**Comment by leandor** [comment]
Sure thing! I'll try to grab an screenie next time I updates mods on Fallout 4... probably over the weekend!

**Comment by leandor** [comment]
As promised, I just updated [this mod](https://www.nexusmods.com/fallout4/mods/47187) and got the warning:

![image](https://user-images.githubusercontent.com/1095373/104828730-2b77e000-584b-11eb-890e-43ac43531620.png)

These are the two mod archives in question (1.4.6 -> 1.4.7)

![image](https://user-images.githubusercontent.com/1095373/104828810-dab4b700-584b-11eb-9448-538c922806f7.png)

If you need anything else, I'll be ready to provide more info!

**Comment by Infernio** [comment]
That's definitely a bug, will have a look tomorrow.

**Comment by Infernio** [comment]
Should be fixed with the newest commit on nightly.

**Comment by leandor** [comment]
Sorry for the late reply! And thanks for the fix! Didn't say anything because I didn't had any mods to update with BA2, to confirm on my side :/ 

As soon as I do, I'll get back with the confirmation!
