### ISSUE TITLE
Consider alternatives to 7zip

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#562]
I've just about had it with this stupid binary. It clearly doesn't *want* to be used via command line.

- The docs are arcane and only found on a [third-party website.](https://sevenzip.osdn.jp)
- Getting progress information from it is almost impossible since it doesn't print with newlines, and instead just updates one line over and over.
  - You can try to read one byte at a time and look for sequences of digits + percentage sign to update the progress bar, but then you lose error handling.
  - Even worse: if you do this and your program doesn't respond fast enough (e.g. if you paused it using a debugger), 7zip crashes with error code 2 (helpfully labeled 'fatal error' in the docs).
- There are no stability guarantees to its output, which has lead to issues like #322.
- It's the primary reason for our `unicodeSafe` hack (though hopefully that one will disappear on py3).
- Context switches are not cheap.
- It's a binary we need to keep in our repo, duh.

Some alternatives are mentioned here: https://stackoverflow.com/questions/32797851/how-to-read-contents-of-7z-file-using-python

- [ ] Blocked on #460

**Comment by Arthmoor** [comment]
If we're targeting Python 3.3 or newer then I'd say just go with the internal lzma support the top answer on stackoverflow mentions.

**Comment by Infernio** [comment]
Read the comments, the builtin one doesn't work for 7z files :P
We might be able to use the builtin one for omods, for which we bundle the lzma.exe right now.

I did some googling though, and patool (https://github.com/wummel/patool) looks promising.

**Comment by lojack5** [comment]
Did a little testing and sniffing:
- [py7zr](https://github.com/miurahr/py7zr) seems nice, no longer need the binaries.  For listing archive contents its actually an order of magnitude quicker than calling into a subprocess.  However for extraction it's about 6x slower (makes sense, it's fully python).  Would be really nice if we could get the performance on par, might play around with cython to see what can happen there.
- [patool](https://github.com/wummel/patool) Nice in that is means less code to maintain, but it essentially does what we do already. Meaning the 7z binary still needs to be somewhere on the user's system that the library can find it. So a little disappointing.

**Comment by Infernio** [comment]
Looks like there's nothing we can do there. So if we ever want to figure this out, we'd have to write a performance-oriented version of it, maybe wrapping something like https://github.com/dyz1990/sevenz-rust into a Python extension.

**Comment by Utumno** [comment]
Yep over the ages that 7z.exe stays till someone writes a PEP for including 7z in the std :P
Plus maybe format limitations - does 7z have a header listing files and their attributes? Or listing involves parsing the output of some exe command (yak) necessarily?

**Comment by Infernio** [comment]
Yeah, it pulls in like 6-7 dependencies from what I saw. I don't really want to add a dependency here unless it *fully* replaces 7z.

**Comment by lojack5** [comment]
@Arthmoor pointed out libarchive, so did another round of tests.  My test archive is a vanilla SEE data folder compressed in 7zip with default options. Listing contents included gathering needed BAIN info (size, mtime, crc)

- EXE: Listing contents ~11ms, full extraction: ~20s
- py7zr: Listing contents ~1.5ms, full extraction: ~140s
- libarchive-c: Listing contents ~0.5ms (!!), full extraction: ~410s :(
- python-libarchive: Haven't been able to get a windows build working yet.

Niggles:
- libarchive-c doesn't do DLL loading properly on windows.  Even with the archive.dll (had to manually download from the libarchive project) in the same folder it fails to load.  Had to monkey patch the loading code to provide the absolute path rather than relative path.
- python-libarchive: no prebuilt binaries on windows.  Pip installing it triggers a build of the source with MSVC build tools (cool) but...seems there's some incompatibilities in the code.  Stuck on `mode_t` not being defined (haven't dug fully into the details of why).  See [python-libarchive#38](https://github.com/smartfile/python-libarchive/issues/38) for someone that got a *little* further than I, but had to patch the code to do so.

Not sure if getting python-libarchive working is worth the trouble, seeing the performance of the ctype wrapper version (libarchive-c).
