### ISSUE TITLE
Add 'Magic: Summoning Absorption Fix' assorted tweak

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#565]
Adds the "No Absorb/Reflect" flag to all summoning spells. The absence of that flag can make summoning spells fail if you have any sources of spell absorption, e.g. perks or spells.
USSEP and its predecessors fix this for all vanilla spells, but mod-added spells often still have this problem.

**Comment by Infernio** [comment]
Closed in 1fc42463fee52a817186b7d4772ddf270af78853.

**Comment by VariableReferee** [comment]
Don't know if anyone reads these comments, but I'd like to report that this tweak works even better than the standard zpatcher for this. All the changes in my zpatch.esp for this were also in my Bashed Patch, but there were *38* records in my Bashed Patch which were NOT in my zpatch.esp. So the new tweak in WB works better because it catches a lot more records. Thanks for the great job.

**Comment by assasinxtg** [comment]
> Don't know if anyone reads these comments, but I'd like to report that this tweak works even better than the standard zpatcher for this. All the changes in my zpatch.esp for this were also in my Bashed Patch, but there were _38_ records in my Bashed Patch which were NOT in my zpatch.esp. So the new tweak in WB works better because it catches a lot more records. Thanks for the great job.

I did.
