### ISSUE TITLE
Load Order Handling Improvements, Part 2

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#578]
Continuing from #309, which was mostly focused on 306/307.

308:
- [x] Update.esm should not be written into plugins.txt for Skyrim LE and newer games (including Enderal). The game hardcodes it to load directly after the game master. Done in 1b412e16398edbf20ef53ab78d5513c367087a72.

309+:
- [ ] games.TimestampGame#_persist_load_order must be rewritten so it makes the least mtimes changes possible - so on creating a new mod for instance and placing it after selected ones assign a mod time +1 sec instead of +60 secs - see _get_free_time_step elimination
- expose saved load orders/active plugins lists and allow the user to edit them - a lot of thinking this needs (UI ?) -> new issue #361 
- revisit undo/redo -> clean invalid ? More traditional undo redo (remove redos on a new load order)-> will be investigated as part of issue #361
- [ ] revisit master/children warnings - add a big fat one for ESM-flagged files that have a non-ESM-flagged file as master

Ut:

- ccc file handling fixups - see https://github.com/orgs/wrye-bash/projects/2/views/1?pane=issue&itemId=65705657 _> new issue #682

**Comment by Infernio** [comment]
I think something regressed with actives cleaning. In Enderal SE, I get this on boot with latest nightly:
```
_games_lo.py  184 _warn_lo: Fixed Load Order: added='None', removed='None', duplicates='lo_duplicates(Enderal - Forgotten Stories.esm), ', reordered from:
Skyrim.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Update.esm
Enderal - Forgotten Stories.esm
Enderal - Forgotten Stories.esm
SkyUI_SE.esp
Bashed Patch, 0.esp
to:
Skyrim.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Update.esm
Enderal - Forgotten Stories.esm
Enderal - Forgotten Stories.esm
SkyUI_SE.esp
Bashed Patch, 0.esp
_games_lo.py  211 _warn_active: Invalid Plugin txt corrected:
Removed duplicate entries from active list : Enderal - Forgotten Stories.esmReordered active plugins with fixed order from:
Skyrim.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Update.esm
Enderal - Forgotten Stories.esm
to:
Skyrim.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Update.esm
Enderal - Forgotten Stories.esm
Enderal - Forgotten Stories.esm
```

**Comment by Infernio** [comment]
Ah, figured it out. Enderal SE has a `Skyrim.ccc` with `Enderal - Forgotten Stories.esm` in it, which meant we got `Enderal - Forgotten Stories.esm` twice in `must_be_active_if_present`. Will push a fixup.

**Comment by Utumno** [comment]
Bash load order APIs are now mature enough to handle foreseeable new games with ease (see [39d0935](https://github.com/wrye-bash/wrye-bash/commit/39d0935ec7d2bdfc6b41bf56357dcd1c08e3ed94)) - apart from general maintenance they need no more real work - however there are some architectural ideas that we could investigate in the far future:

- keep lo as a dict[fn, is_active] - when [`LoadOrder`](c39b87797392f0821205d6e3ede0a1ece78a1432) was born (py2, almost ten years ago) ordered dicts were not even on the horizon, now well into python3 seems we keep two independent structures that should be tied together. Even if we decide this is not practical (cause we would need to extract, say, active list from the dict, or cache it anyway) tying active and lo would give interesting insights on atomicity of operations - and much cleaner when-to-write checks
- orthogonal to it, ModInfo could hold some of the load order info - this might be completely wrong (think locking load order and co) but trying to implement some of it would again give precious insight on the redundancy (or not) of some of the (currently three) levels of load order handling (`_game_lo <- load_order <- ModInfos/_lo_cache`)

And some more #300 material from the OP:

- [ ] games.TimestampGame#_persist_load_order must be rewritten so it makes the least mtimes changes possible - so on creating a new mod for instance and placing it after selected ones assign a mod time +1 sec instead of +60 secs - see _get_free_time_step elimination
- [ ] revisit master/children warnings - add a big fat one for ESM-flagged files that have a non-ESM-flagged file as master
