### ISSUE TITLE
309.1 not Installing Readme Files

### ISSUE THREAD

**Issue by AndalayBay** [wrye-bash/wrye-bash#626]
I asked about this issue on Discord and got ignored.

Bash won't install a readme file at the root of the archive if it doesn't have "readme" in the name. For example, Roads of Cyrodiil [https://www.afkmods.com/index.php?/files/file/259-roads-of-cyrodiil/](https://www.afkmods.com/index.php?/files/file/259-roads-of-cyrodiil/)
It won't install "Roads of Cyrodiil.txt". It will however install any text file if it's in a folder - no matter the name. Or it will install a text file at the root if it has "readme" in the name. I right-clicked on the archive and selected Override Skips and it didn't make any difference. I also clicked on Has Extra Directories and that didn't help either.

This works just fine in 307. I know you guys have some stuff about archives being organized a certain way, but I'm not going to repackage all my mods just so Bash installs them properly. These are mods I didn't create.

**Comment by Infernio** [comment]
You almost certainly didn't get ignored, your post just got buried. We are all volunteers and have busy lives outside of maintaining an open source project for free, which means we miss messages - especially if we wake up and see 50+ new messages on the Discord.

The proper course of action in such a situation is to simply post your message in the forum/server again after it hasn't received a response for a while - and if that still doesn't get a response, feel free to ping `@Developers` on the Discord.

As for this report, I'm on mobile right now and hence can't determine if this is a legitimate bug. I'll try to take a look tomorrow, if I have time.

**Comment by Infernio** [comment]
> This works just fine in 307.

It actually doesn't:

![image](https://user-images.githubusercontent.com/2845240/152639040-ede3c309-e616-451b-89df-990859d46929.png)

That's because WB has always just looked for files with something like `readme` (or `lisezmoi`, interestingly) in their names:

- dev: https://github.com/wrye-bash/wrye-bash/blob/8b2e673077eb7442f8fa9587732826daa8da36e1/Mopy/bash/bosh/bain.py#L77-L79

- 307: https://github.com/wrye-bash/wrye-bash/blob/8e1929166d657cfe11ed61dd8bb9dbcc8f81e6ec/Mopy/bash/bosh/bain.py#L76-L78

I've gone ahead and refactored/fixed all this up. It now works as expected in the newest nightly (`310.202202051256`):

![image](https://user-images.githubusercontent.com/2845240/152643121-933dd89f-0f98-40ff-ab67-f9afd38c3ec7.png)

There is an open issue for making this work better (#40), so closing this in favor of that issue.
