### ISSUE TITLE
Add support for Starfield updates up to v1.14

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#681]
- [ ] The save header has changed quite a bit, so we'll need to investigate exactly what changed
  - [ ] There is a [new block](https://github.com/Nexus-Mods/StarfieldSaveTool?tab=readme-ov-file#plugin_info) for medium plugins, similar to the small & full plugin blocks. This was added in v1.11
  - [ ] Some plugins have [extra data](https://github.com/Nexus-Mods/StarfieldSaveTool?tab=readme-ov-file#extra-data) as of v1.12
  - Here are some saves from various versions for testing: [saves.zip](https://github.com/user-attachments/files/16301956/saves.zip)
- [ ] A new file type was added (medium) that's between ESL (small) & ESM (full). It occupies the `FD` load order index, & form IDs follow the format `FDxxYYYY` where `xx` is the index & `YYYY` is the record ID. That means there's a hard limit of 256 medium plugins, & the hard limit for full plugins has dropped to 253 when medium plugins are present
- [ ] Load order is a bit of a mess, see loot/loot#1989 & loot/loot#2032
  - [ ] The way LOOT is handling late-loading vanilla plugins is by writing them to Starfield.ccc to force them to load early. WB should probably do this too
  - [ ] This behavior has changed back to SSE/FO4 behavior in v1.14, so writing to CCC file is no longer necessary
- [ ] The overlay flag [no longer allows](https://github.com/Ortham/libloadorder/issues/97#issuecomment-2179290135) plugins to not take up an LO slot. It also appears to be known internally as the [update flag](https://github.com/Ortham/libloadorder/issues/97#issuecomment-2186991669) & may be related to version control

**Comment by Xeraster** [comment]
Have they figured out how exactly to enable mods yet for Starfield or are they still trying to find a way? I've been trying to enable my bare minimum essential mods manually but I can't because mo2 never works for me (Linux). This one isn't compatible with Starfield ever since Bethesda put out that update that neuters the entire mod situation to make mods hard to install like in Skyrim Special Edition.

Based on the fact the new Starfield update changes the way mods work and the fact that the method I came up with to enable mods manually on Skyrim Special Edition without a mod loader doesn't work on Starfield, it looks like no one actually knows how to or if its possible to enable non creation-store mods in Starfield yet. If this is incorrect, I would love to know which files can be manually modified to get those esm files to load. Otherwise, I'm going to keep trying to find some way so that maybe someone can make a working Starfield mod loader some day. If I figure it out I'll post about it.

**Comment by sibir-ine** [comment]
@Xeraster, as the error says, bug reports should go to AFK Mods or Discord, we can help you better in one of those places.

**Comment by Utumno** [comment]
If you can give me a rundown of what is the current (LOOT?) spec for the handling of the CCC file by Starfield, I could hash up an implementation based on b6553f3e123cacc3c28b67e10e57563602f3a695 - will go ahead and merge that one should be correct although implementing SF handling we can make sure it's final.

**Comment by Infernio** [comment]
I'm assuming that's directed at @sibir-ine? I have absolutely zero knowledge regarding recent Starfield stuff (and don't want to learn it, either - Starfield has left me completely demotivated to work on support for it in WB :/).

**Comment by Utumno** [comment]
sibir or @Ortham or @Arthmoor - anyone who might know so we close this :P

From the perspective of coding the interesting thing here is if _game_lo can be extended - I believe it can from what I gathered from the linked posts.Then _game_lo is final and I can happily flowerbed #578

**Comment by Ortham** [comment]
I don't know if there will be any new files to add to the CCC file, though it seems possible given the recent update that  I wouldn't be surprised if the DLC plugin is hardcoded to load like the other official plugins when that releases.

Personally, I'd just release whatever you've got, and deal with updates as they come. I've yet to release LOOT's blueprint plugin support, so it currently shows `BlueprintShips-Starfield.esm` in the wrong place, but that's just because I've not set aside the time to release it yet, AFAIK it's all ready to go.

**Comment by Arthmoor** [comment]
If you're asking how it works, it's basically just like the one for Skyrim SE. A list of files to load in a specified order.

Wrye Bash already has all of the current files in the proper order in whichever nightly I'm using. So that's probably what ought to go in the .ccc file I guess?

**Comment by Utumno** [comment]
IIUC LOOT writes out a CCC file if not present (cf the OP here). Should we write the CCC file adding:

            'Constellation.esm', 'OldMars.esm', 'BlueprintShips-Starfield.esm',
            'SFBGS007.esm', 'SFBGS008.esm', 'SFBGS006.esm', 'SFBGS003.esm',
            'SFBGS004.esm',

in this order (that is what we have currently/nightly)

**Comment by Ortham** [comment]
That would match what LOOT and MO2 write (though MO2 is missing `SFBGS004.esm`).

**Comment by Utumno** [comment]
Thanks @Ortham - currently Bash does not write a CCC file for any game if there is not one present - does LOOT write out a CCC file only for SF?

**Comment by Ortham** [comment]
> Thanks @Ortham - currently Bash does not write a CCC file for any game if there is not one present - does LOOT write out a CCC file only for SF?

Yes, it's only for Starfield, and it'll write it whenever you open LOOT for Starfield or switch to Starfield once LOOT is open. I think MO2 has a setting that controls whether it writes the CCC file for Starfield, and I don't think it does it for any other game.

**Comment by Infernio** [comment]
Writing it for any other game makes no sense either, the file has sensible content in those games and wiuld get overwritten whenever a player validates game files/updates the game.

**Comment by Utumno** [comment]
Thanks - should be easy to add writing the CCC file for SF only - meanwhile it seems that my initial attempt at #682 needs some fixes - https://discord.com/channels/537706885965676554/537710082755133460/1284473528040558625

**Comment by Utumno** [comment]
Latest nightly should write out a CCC file if not existing

**Comment by LordNyriox** [comment]
@Utumno: 

> Any other load order related thing that should be still implemented? 

You might want to add recognition for the ‘Blueprint’ plugin flag (`0x800`), used in `BlueprintShips-Starfield.esm`. 

As of Starfield v1.12, this flag forces a plugin to load last (regardless of index), and therefore override any other plugins changing the same records.  Only a plugin with the Blueprint flag can override another plugin with the Blueprint flag.

**Comment by Utumno** [comment]
> As of Starfield v1.12, this flag forces a plugin to load last (regardless of its FormID prefix)

What is the FormID prefix? If it is the loadorder part of the formId then this means that Blueprint should have `FE` load order index or `FD` (but what about medium plugins/esls?) - and not a load order index `03` which Bash will assign it now (see the order of plugins posted above).

Are the re any up to date links detailing the LO and plugin format changes?

**Comment by Infernio** [comment]
Or does "load last" just mean it gets reordered to be the last-loading plugin in the list, without it being assigned a fixed FormID prefix?

**Comment by Ortham** [comment]
> What is the FormID prefix?

It's whatever the previous plugin's index is +1, it's not a fixed index. Blueprint plugins can be light/medium flagged though, and so will be given a prefix in their respective FE/FD block.

> Are there any up to date links detailing the LO and plugin format changes?

I think everything about blueprint plugins is covered in loot/loot#2009, and summarised in a [blog post](https://blog.ortham.net/posts/2024-07-30-blueprint-plugins/) that I wrote. The blog post also starts with a link to an earlier post that covers the other load order changes in Starfield.

> Or does "load last" just mean it gets reordered to be the last-loading plugin in the list, without it being assigned a fixed FormID prefix?

Yes.

**Comment by Utumno** [comment]
Going through Ortham's very detailed posts (thanks!) - seems we need some new code - I think small/medium/full must be some kind of enum while blueprint/update another flag (update we call overlay IIUC - maybe call them also update to standardize terminology?) - messy as those flags may or may not be exclusive.

EDIT: didn't press enter - meanwhile I have launched a full attack on the mess that is our plugins type handling - granted esl was a special case but now the plugin types proliferate we need to standardize our handling - part 1 will not add medium/blueprint, will just refactor the code to handle flags and plugin types in a more unified way. More on this hopefully soon(TM)

**Comment by Infernio** [comment]
Yes, overlay is what we came up with as a name before Beth released the CK. Now it's called "update". They also broke the flag completely, so we need to rip half of that handling out at some point 🙃

**Comment by Utumno** [comment]
With the new plugin types the ifelseheimer disease became terminal - is_esl/overlay..., game.has_esl/overlay, has_XXX_flag, recalc_XXX etc - impossible to extend our current handling. Enter PluginFlag (WIP!) https://github.com/wrye-bash/wrye-bash/compare/nightly...ut-681-xxx-plugin-flags. Have a look (needs more till it absorbs all the APIs (mod checker, flip links etc)) but it all comes together beautifully I think. It is largely untested, would be great if you test this build @wrye-bash/bashers:

https://github.com/wrye-bash/wrye-bash/actions/runs/10980669262/artifacts/1963077231

especially the flip links. I also stop excluding "Overlay" (naming will be done last!) plugins from load order in 8386753f9d0984499f0cb9e7c0254456828a92eb - so Starfield needs some testing too. While I am finalizing would be helpful if some one, more versed in the overlay code, could check what other Overlay changes would need be reverted.

**Comment by Ortham** [comment]
FYI, Starfield changed stuff again, the official plugins (aside from `BlueprintShips-Starfield.esm`) now have hardcoded positions. I've just released a LOOT update to reflect the changes (and including blueprint plugin support), and part of that is that LOOT no longer writes `Starfield.ccc`. `Starfield.ccc` can still be used to load plugins before those in `Plugins.txt` though. See loot/loot#2032 for more details, I'll probably write up what I know in a blog post too.

**Comment by LordNyriox** [comment]
@Ortham: 

> LOOT no longer writes `Starfield.ccc`. 

**Request:** Is there any chance you can write ‘Blueprint Master’ plugins to `Starfield.ccc`, at least? 

Since the game removes those plugins from `plugins.txt`, I suspect that would be the only way to guarantee that overrides to `BlueprintShips-Starfield.esm` will load.

**Comment by Utumno** [comment]
> BlueprintShips-Starfield.esm

IIUC Ortham's comments (thanks!) neither `BlueprintShips-Starfield.esm` nor in general blueprint flagged plugins are removed from plugins.txt - just `BlueprintShips-Starfield.esm` is active if present - however it can be moved freely via the plugins txt.

**Comment by Ortham** [comment]
@LordNyriox I considered it, and may do so in the future, but the handling of blueprint masters by the game is awkward and writing the to the CCC file is a bit of a hack, and AFAIK blueprint masters are rare enough that I'd rather take a conservative approach and have people deal with them manually, at least for now.

@Utumno Unfortunately no, blueprint masters are removed from Plugins.txt by the game after they're loaded, so the only way to persist them being active alongside other plugins is to put them in Starfield.ccc.

**Comment by Utumno** [comment]
Hmm - so hijack Starfield.ccc to write in it all Blueprint Masters (as the user orders them)? What should we do with existing Starfield.ccc we wrote out? Alternatively we could just add the `BlueprintShips-Starfield.esm` to the ccc file making sure it loads first (in the BM block). That would not persist the order other BM plugins load relative to each other, but then it's weird the game removes them after loading them (presumably in the order it finds them in Plugins.txt the first time?). Would that mean that the game reads the order from the save maybe?

**Comment by Ortham** [comment]
> presumably in the order it finds them in Plugins.txt the first time?

Yes

> Would that mean that the game reads the order from the save maybe?

AFAICT if you add blueprint masters to Plugins.txt then launch the game, the game will load them in the order they're listed, then remove them from Plugins.txt. If you then relaunch the game (maybe loading a save is enough, I've only tested with fresh launches), then the game will not load the blueprint masters (apart from `BluerpintShips-Starfield.esm`, since it's always active). Starfield does check a save's load order when you load ask to load it, but AFAICT that's only to display warning dialogs if there are missing plugins or the load order has changed - I don't think it'll ever silently force a save's load order.

**Comment by Utumno** [comment]
>  If you then relaunch the game [...] the game will not load the blueprint masters

It's this bit that escapes me really - so what is the use of BMs if the game will not load them? Hope I am not being dumb trying to catch up

**Comment by Ortham** [comment]
> It's this bit that escapes me really - so what is the use of BMs if the game will not load them? Hope I am not being dumb - trying to catch up

The game will load them, but then remove them from `Plugins.txt` after, so putting them in `Plugins.txt` basically only works once.

**Comment by Utumno** [comment]
Thanks @Ortham - this would really mean that all BM plugins are implicitly active? Then if the order is respected when first loaded (and present in the plugins.txt), is it the same order that the game assigns them on relaunch (after it has removed them from the plugins txt)? You mention about implicitly active plugins in https://blog.ortham.net/posts/2024-06-28-load-order-in-starfield/ that:

> Any plugins that are active but have no defined load order position (e.g. because they’re implicitly active or activated using sTestFile<N> and aren’t otherwise constrained) are appended to the load order in order of ascending file modification timestamp (so more-recently-modified plugins load later). Unlike all previous games, if two plugins loaded this way have the same timestamp, they’re loaded in ascending filename order, not descending filename order.

(disclaimer: sTestFile<N> load order is out of scope :P)

If indeed BMs are implicitly active then we should probably go for this sorting and allow users to modify timestamps to resort. Seems cleaner to avoid messing with the Starfield.ccc and the plugins txt - actually we should remove them from there when we encounter them first while carrying the order over.

**Comment by Ortham** [comment]
> Thanks @Ortham - this would really mean that all BM plugins are implicitly active?

No, only `BlueprintShips-Starfield.esm` is implicitly active, so unfortunately I think trying to manage their load order using just timestamps isn't feasible, since then you could never have them active.

Also worth noting that I haven't retested the timestamp stuff since June, I'm only assuming it hasn't changed.

**Comment by Utumno** [comment]
Thanks - but if not implicitly active and removed from the plugins txt - are they ever active (apart from when they are loaded from plugins.txt the first time the game finds them there)

> so putting them in Plugins.txt basically only works once.

After that one time they are never active then? except if one added them to the plugins txt or Starfield.ccc

Are then they meant only for official plugins like `BlueprintShips-Starfield.esm`? In that case what should we do - write all the BM masters the user activates in Starfield.ccc as suggested by LordNyriox? Should we just append to the Starfield.ccc opr overwrite? What happens if the file has duplicate entries - we keep first or last (might result in different load orders)?

I am not expecting any answers just trying to see IIUC - or if I am missing something important

**Comment by LordNyriox** [comment]
@Utumno: 

> I still don't get that "load once" behavior 

In short, the game itself will remove any plugins it deems ‘improper’ from `plugins.txt`—but this function is executed *after* the function that actually loads plugins from `plugins.txt`.

**Comment by LordNyriox** [comment]
@Utumno: 

> I still don't get that "load once" behavior 

In short, the game itself will remove any plugins it deems ‘improper’ from `plugins.txt` (which includes both ‘Blueprint Masters’ and hardcoded plugins)—but this function is only executed *after* the function that actually loads plugins from `plugins.txt`.

**Comment by Utumno** [comment]
Here is a build adding Blueprint support https://github.com/wrye-bash/wrye-bash/actions/runs/11224940400/artifacts/2026516193 - might blow on load but should be easy to fix I have not Starfield and can't run it - please test (and let me know what the color for blueprint/blueprint masters should be :P). I am thinking that maybe the scale flags (medium esl should be coded by the background (say green for esl ? for mid and white for full plugins) - while master flag status by the text (blue for ESM blue? for blueprint blue^2 for blueprint masters). Overlay (aka update) I am not sure. I also added a color for flag conflicts currently (255, 0,0). Not everything was implemented but then do we want to allow flagging with all the new flags, adding all these flags to the settings, checking with the mod checker etc? Might not worth the hassle (after all we are not really sure what those do - especially the update/overlay we should probably revert the "mergeability" and new plugin flags)

**Comment by Infernio** [comment]
Half of these flags seem useless for mods (like Overlay/Update and Blueprint), plus Bethesda keeps changing what they mean. I'd hold off on colors for them for now (plus changing ESL coloring now would be quite confusing for SSE and FO4 users), maybe just add them to the status bar explanation text.

**Comment by Infernio** [comment]
In the future, we might consider "weight" (light/medium/full) as a change to the checkbox (e.g. its shape, we're not using that for anything on the Mods tab yet).

**Comment by Utumno** [comment]
We might fill an issue for revisiting display of plugin scale/master/blueprint status as well as errors when the dust settles but yes too early still. We do need a `'mods.text.flags_conflict'` (text? background?) color - currently (255, 0 ,0). The nice part is that the plugin types logic is now in _init_plugin_flags instead of in _set_color/constants.py etc - see 363aee59876a19c0d382d860e0c5c20485c11e1b

This was a huge digression but I think we need to support at least the new plugin types and the load order (implemented for blueprint but needs testing). Then we should release with this support and leave saves for 314 - although I suspect it's plugins related changes we might address while implementing medium plugins (more colors...)

**Comment by LordNyriox** [comment]
@Infernio: 

> Half of these flags seem useless for mods (like Overlay/Update and Blueprint) 

Slight correction: If a modder wants to directly modify any of the vanilla ship templates (most of which are in `BlueprintShips-Starfield.esm`), said modder would have to flag his or her plugin as a ‘Blueprint Master’. 

Other than that one case, I agree with you.

**Comment by Utumno** [comment]
@Arthmoor raised an issue about the order of the masters differing from load order (see https://discord.com/channels/537706885965676554/537710082755133460/1295862931036311625):

> Also not sure how relevant it is to things but the order of the SFBGSxxx files for Starfield listed as they currently are is NOT the same as the order the CK will put them in.
> Even if you somehow manage to force the order outside of the CK, the next time the mod gets saved it puts them back into the following order:
> SFBGS004.esm
> SFBGS007.esm
> SFBGS008.esm
> SFBGS003.esm
> SFBGS006.esm

Given that reordering the masters for a Starfield plugin is currently an unsafe operation, I'm not sure it's a good idea for everyone to have agreed to list them in numerical order since this goes against the CK's forced behavior for these files.

result is we warn for out of orders masters. We could go about it in different ways but finally what's the deal - my guess is that the SF***XX plugins do not override each other so their respective order is unimportant. In that case we could not warn if:

- all the out-of-order masters are present (else we warn on missing master which is more severe)
- none of them depends one each other

**Comment by Ortham** [comment]
I'm not sure if the official masters have any conflicts between each other, I assume not.

FWIW I'd be happy to change LOOT to read their load order in the order Arthmoor gave, so that it matches what the CK uses - I only put them in ascending numerical order because that seemed obvious and I didn't know of anything else to go on.

**Comment by Utumno** [comment]
But then the game is to assign a different index to those (supposedly the SFBGSxxx are loaded by the game in the order we force now, which is ascending in the filename). Not sure if LOOT warns for out of order masters but for us I think safest is to suppress the warning - not sure about the right check though.

**Comment by Arthmoor** [comment]
There are only 2 minor conflicts in the official masters, both of them between the SFBGS003.esm and SFBGS008.esm files.

With the order as specified currently, the 003 file loses them both and there's a good chance it should not.

**Comment by Utumno** [comment]
> There are only 2 minor conflicts in the official masters, both of them between the SFBGS003.esm and SFBGS008.esm files.
> 
> With the order as specified currently, the 003 file loses them both and there's a good chance it should not.

So what is the winning records in a vanilla v1.14 setup? If the 003 does lose them and it shouldn't then these two records should probably land on the USFP. Still indeed my heuristics would not help.

**Comment by Arthmoor** [comment]
Assuming numerical order is how the game reads the files, then the 008 file will override the 2 minor changes from the 003 file. It's not necessarily going to break something but right now the unresolvable conflict between how the CK sets the MAST record and what the game expects means it's difficult to know how to proceed from here.

What I think is needed is some level of definitive proof of the game's load ordering. The order the CK chooses doesn't appear to be logically based. It's not date related which would be the only other method that would make sense. So the list must be getting set somewhere by the .exe itself.

**Comment by Ortham** [comment]
> What I think is needed is some level of definitive proof of the game's load ordering.

I created a plugin that overrode `0002290F` (it's a book) and used that to replace all the official plugins (setting the right small/medium flags as necessary) apart from `Starfield.esm` and `BlueprintShips-Starfield.esm`, setting a different name for each plugin, and then checked which plugin's name change I could see in-game, then replacing that plugin with the original and checking again, until I'd reinstated all the original official plugins.

That gave the following load order:

```
Constellation.esm
OldMars.esm
ShatteredSpace.esm
SFBGS003.esm
SFBGS004.esm
SFBGS006.esm
SFBGS007.esm
SFBGS008.esm
```

**Comment by Utumno** [comment]
Thanks @Ortham that's very helpful. So it seems we keep the order as in here and we should suppress the warning for the out of order masters due to the CK (soon).

Meanwhile I have been busy with saves <-> MID plugins support - new build here: https://github.com/wrye-bash/wrye-bash/actions/runs/11489168227/artifacts/2096221100

I still miss some (like plugin counts deactivate message etc) but I think we are almost done. Give it a whirl :)

**Comment by Utumno** [comment]
@Ortham @Arthmoor - it's maybe worth noting that SFBGS003.esm and SFBGS006.esm, which are the ones that the CK orders differently, are medium plugins. In save masters they come
indeed in a separate block that is located right after the esl block - but not sure if this matters for the plugin masters

----

Pushed a final version of SF support here: https://github.com/wrye-bash/wrye-bash/actions/runs/11544579356/artifacts/2109854074 - last chance to change the MID color. This also includes some load order fixups - Bash will remove the vanilla masters from the plugins.txt but will not remove Blueprint masters - if not present in plugins.txt, Bash will add those back to its load order internally in ascending time/name order - see 3f735db0c2d8b595611ade80081f3907e8dc4cff

**Comment by Utumno** [comment]
Basic SF support is now merged - more exotic features as (see https://blog.ortham.net/posts/2024-06-28-load-order-in-starfield/#load-order):

- implementing a special IniLoGame with `sTestFile` keys - the building blocks are there but our load order handling needs to be able to change on the fly (what if one edits the ini, removing the sTestFile lines - we must fallback to current SF lo handling)
- multiple data dirs (<game install path>\Data) - this will need #353 be closed shut - as this involves a higher-than-datastore RefreshData class that will sacn dirs once - then usu the now pointless info_dir attr
- bashed patch - duh, records, hundreds of them

must wait till we have more coding hands.

I have a couple bonus questions:

> Unlike all previous games, if two plugins loaded this way have the same timestamp, they’re loaded in ascending filename order, not descending filename order. (from blog post above)

Well seem that Bash has always been assigning them the _ascending_ order (Oblivion/FO3/FNV) - I should fix but I would need a second pair of brains

And bonus^2 - how does the game(s) treat duplicates in plugins.txt (or the ccc file)? Bash keeps the first entry but that's completely untested

**Comment by Ortham** [comment]
> And bonus^2 - how does the game(s) treat duplicates in plugins.txt (or the ccc file)? Bash keeps the first entry but that's completely untested

FWIW, my libloadorder library:

- keeps the first entry when loading plugins from the CCC file
- keeps the last entry when loading plugins from Plugins.txt

Unfortunately I can't remember if any of my notes cover why, and I don't think I've got any test cases that explicitly spell out why either, but keeping the last entry involves doing more work so I assume I had some reason to do that...
