### ISSUE TITLE
CCC fallback isn't accurate to game behavior

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#682]
https://discord.com/channels/537706885965676554/537710082755133460/1247023734372438058

If the CCC file is missing, CC plugins need to be activated via `plugins.txt`. However, in this case, WB treats all plugins in the fallback list as active if present & removes them from `plugins.txt`.

Since the purpose of the fallback list is to prevent the user from reordering them, additional logic is required to lock their load order but keep them in `plugins.txt` (& possibly enforce their active status in `plugins.txt` if also desired).

Utumno: ref #578

**Comment by Utumno** [comment]
Continuing from https://discord.com/channels/537706885965676554/537710082755133460/1260535806733455360

@sibir-ine:

> If the CCC file is present, ccc_fallback shouldn't be used at all. ccc_fallback should just be used to provide a preset order for the CC plugins that users can't manipulate if their CCC file is missing or unreadable for whatever reason. _They'll then need to be written to plugins.txt in that order as well_.

So if the ccc file is present we keep (for whatever plugins it has in there) the order (they appear) in the ccc file? And only use the ccc_fallback if the ccc file is missing, as you say. I had the impression the order the ccc plugins load is hardcoded - it's the one in the ccc_fallback. Of course then if a plugin is present in the ccc file and not in ccc_fallback we would not know its load order. And bonus question - what if a plugin in must_be_active_if_present appears in the ccc file? Will the game load it in the   order it is in the ccc file or still before the plugins in the ccc file?

**Comment by Infernio** [comment]
We should never allow a user to break CCC order, even if the file is missing. That was the purpose of the fallback. The game itself apparently lets you do whatever you want if the CCC file is missing, but that is guaranteed to break things.

The difference for us is: if the CCC file is missing, we have to write the CC files into plugins.txt. Otherwise, we should not write them and even remove them, because the order might be wrong - if the CCC file is present, that forces the game to load and order them as specified in that file.
